// examples/chat-svelte/src/components/chat-list/ChatList.svelte
<script lang="ts">
  import { co } from 'jazz-tools';
  import { AccountCoState } from 'jazz-tools/svelte';
  import { Lock, MessageSquarePlus } from 'lucide-svelte';
  import ChatListItem from '@/components/chat-list/ChatListItem.svelte';
  import { Button } from '@/components/ui/button';
  import { navigate } from '@/lib/router';
  import { Chat, ChatAccount } from '@/lib/schema';

  const account = new AccountCoState(ChatAccount, {
    resolve: {
      root: {
        chats: { $each: true }
      }
    }
  });
  const me = $derived(account.current);

  const chats = $derived(
    me.$isLoaded
      ? Object.values(me.root.chats).sort(
          (a, b) =>
            new Date(b.$jazz.createdAt || 0).getTime() - new Date(a.$jazz.createdAt || 0).getTime()
        )
      : []
  );

  async function createPrivateChat() {
    if (!me.$isLoaded) return;
    const privateGroup = co.group().create();
    const chat = Chat.create(
      [
        {
          text: 'This is a private chat.',
          reactions: []
        }
      ],
      { owner: privateGroup }
    );
    me.root.chats.$jazz.set(chat.$jazz.id, chat);
    navigate(`#/chat/${chat.$jazz.id}`);
  }
</script>

<div class="p-2 flex flex-col gap-2">
  <div class="grid grid-cols-2 gap-2">
    <Button onclick={() => navigate('#/')}>
      <MessageSquarePlus class="size-4" /> New Chat
    </Button>
    <Button variant="outline" onclick={createPrivateChat}>
      <Lock class="size-4" /> New Private Chat
    </Button>
  </div>

  {#if me.$isLoaded}
    {#each chats as chat}
      <ChatListItem
        chatId={chat.$jazz.id}
        onDelete={() => me.root.chats.$jazz.delete(chat.$jazz.id)}
      />
    {/each}
  {:else}
    <p class="text-muted-foreground text-sm p-4">Loading...</p>
  {/if}
</div>

// examples/chat-reatom-react/src/components/chat-list/ChatList.tsx
import { reatomComponent } from "@reatom/react";
import { wrap } from "@reatom/core";
import { LockIcon, MessageSquarePlusIcon } from "lucide-react";
import type { DurabilityTier } from "jazz-tools";
import { ChatListItem } from "@/components/chat-list/ChatListItem";
import { Button } from "@/components/ui/button";
import { jazz } from "@/jazz";
import { myProfile } from "@/model/my-profile";
import { myMembershipsQuery } from "@/model/queries";
import { chatRoute } from "@/routes";
import { app } from "../../../schema.js";

export const ChatList = reatomComponent(() => {
  const { db, session } = jazz();
  const profile = myProfile();
  const userId = session?.user_id ?? null;
  const sharedWriteOptions: { tier: DurabilityTier } = {
    tier: db.getConfig().serverUrl ? "edge" : "local",
  };

  const memberships = myMembershipsQuery();

  const createPublicChat = wrap(async () => {
    if (!userId || !profile) return;

    const chat = await wrap(
      db
        .insert(app.chats, {
          isPublic: true,
          createdBy: userId,
        })
        .wait(sharedWriteOptions),
    );
    await wrap(db.insert(app.chatMembers, { chatId: chat.id, userId }).wait(sharedWriteOptions));
    await wrap(
      db
        .insert(app.messages, {
          chatId: chat.id,
          text: "Hello world",
          senderId: profile.id,
          createdAt: new Date(),
        })
        .wait(sharedWriteOptions),
    );

    chatRoute.go({ chatId: chat.id });
  });

  const createPrivateChat = wrap(async () => {
    if (!userId || !profile) return;

    const shareCode = crypto.randomUUID().slice(0, 8);

    const chat = await wrap(
      db
        .insert(app.chats, {
          isPublic: false,
          createdBy: userId,
          joinCode: shareCode,
        })
        .wait(sharedWriteOptions),
    );
    await wrap(
      db
        .insert(app.chatMembers, {
          chatId: chat.id,
          userId,
          joinCode: shareCode,
        })
        .wait(sharedWriteOptions),
    );
    await wrap(
      db
        .insert(app.messages, {
          chatId: chat.id,
          text: "This is a private chat.",
          senderId: profile.id,
          createdAt: new Date(),
        })
        .wait(sharedWriteOptions),
    );

    chatRoute.go({ chatId: chat.id });
  });

  return (
    <div className="p-2 flex flex-col gap-2">
      <div className="grid grid-cols-2 gap-2">
        <Button onClick={createPublicChat}>
          <MessageSquarePlusIcon /> New Chat
        </Button>
        <Button variant="outline" onClick={createPrivateChat}>
          <LockIcon /> New Private Chat
        </Button>
      </div>

      {memberships.map((membership) => {
        // .include() type info is erased at runtime; chat is Chat at runtime
        const chat = membership.chat as unknown as
          | { id: string; isPublic: boolean; name?: string }
          | undefined;
        return (
          <ChatListItem
            key={membership.id}
            chatId={chat?.id ?? membership.id}
            chat={chat}
            onDelete={() => db.delete(app.chatMembers, membership.id)}
          />
        );
      })}
    </div>
  );
}, "ChatList");
