// packages/jazz-tools/src/solid/provider.tsx
import { createContext, useContext, type JSX, type Accessor, Show } from "solid-js";
import type { Session } from "../runtime/context.js";
import {
  isPendingSolidJazzClientReady,
  type SolidJazzClient,
  type PendingSolidJazzClient,
} from "./create-solid-jazz-client.js";
import { Db } from "../runtime/db.js";

type JazzClientContextValue = SolidJazzClient;

export const JazzClientContext = createContext<JazzClientContextValue | undefined>(undefined);

export type JazzProviderProps = {
  client: PendingSolidJazzClient;
  fallback?: JSX.Element;
  children: JSX.Element;
};

export function JazzProvider(props: JazzProviderProps) {
  const clientReady = () =>
    isPendingSolidJazzClientReady(props.client) ? props.client : undefined;

  return (
    <Show when={clientReady()} keyed fallback={props.fallback ?? null}>
      {(client) => (
        <JazzClientContext.Provider value={client}>{props.children}</JazzClientContext.Provider>
      )}
    </Show>
  );
}

export function useJazzClient(): JazzClientContextValue {
  const ctx = useContext(JazzClientContext);
  if (!ctx) throw new Error("useJazzClient must be used inside JazzProvider.");
  return ctx;
}

export function useDb<TDb = Db>(): Accessor<TDb> {
  const client = useJazzClient();
  return () => client.db as TDb;
}

export function useSession(): Accessor<Session | null> {
  const client = useJazzClient();
  return () => client.session;
}

export function useAuthState() {
  const client = useJazzClient();
  return () => client.authState;
}

// packages/jazz-tools/src/react-core/provider.tsx
import { createContext, use, useContext, type ReactNode } from "react";
import type { Session } from "../runtime/context.js";
import type { SubscriptionsOrchestrator } from "../subscriptions-orchestrator.js";

type CoreJazzClient = {
  db: unknown;
  manager: SubscriptionsOrchestrator;
  session?: Session | null;
  shutdown: () => Promise<void>;
};

type JazzProviderClientProps = {
  client: CoreJazzClient | Promise<CoreJazzClient>;
  children: ReactNode;
};

export type JazzProviderProps = JazzProviderClientProps;

const JazzContext = createContext<CoreJazzClient | null>(null);

export function JazzProvider({ client, children }: JazzProviderProps) {
  const isPromiseLike = typeof client === "object" && client !== null && "then" in client;
  const resolvedClient = isPromiseLike ? use(client) : client;

  if (!resolvedClient) {
    throw new Error("JazzProvider requires a `client` prop.");
  }

  return <JazzContext.Provider value={resolvedClient}>{children}</JazzContext.Provider>;
}

export function useJazzClient(): CoreJazzClient {
  const ctx = useContext(JazzContext);
  if (!ctx) throw new Error("useDb must be used within <JazzProvider>");
  return ctx;
}

export function useDb<TDb = unknown>(): TDb {
  return useJazzClient().db as TDb;
}

export function useSession(): Session | null {
  return useJazzClient().session ?? null;
}
