// packages/jazz-tools/src/solid/testing.ts
import { Account, AnonymousJazzAgent, AuthSecretStorage } from "jazz-tools";
import { TestJazzContextManager } from "jazz-tools/testing";
import { type Accessor, createMemo } from "solid-js";
import { JAZZ_AUTH_CTX, JAZZ_CTX, type JazzContextValue } from "./jazz.js";

export function createJazzTestContext<Acc extends Account>(
  opts: {
    account?: Acc | { guest: AnonymousJazzAgent };
    isAuthenticated?: boolean;
  } = {},
) {
  const ctx = new Map<
    typeof JAZZ_CTX | typeof JAZZ_AUTH_CTX,
    JazzContextValue<Acc> | Accessor<AuthSecretStorage>
  >();

  const account = () => opts.account ?? (Account.getMe() as Acc);

  const value = createMemo(() =>
    TestJazzContextManager.fromAccountOrGuest<Acc>(account(), {
      isAuthenticated: opts.isAuthenticated,
    }),
  );

  const jazzContextValue = () => value().getCurrentValue();
  const authStorageValue = () => value().getAuthSecretStorage();

  ctx.set(JAZZ_AUTH_CTX, authStorageValue);
  ctx.set(JAZZ_CTX, { current: jazzContextValue });

  return ctx;
}

export {
  createJazzTestAccount,
  createJazzTestGuest,
  linkAccounts,
  setActiveAccount,
  setupJazzTestSync,
} from "jazz-tools/testing";

// packages/jazz-tools/src/react-core/testing.tsx
import { Account, AnonymousJazzAgent } from "jazz-tools";
import { TestJazzContextManager } from "jazz-tools/testing";
import { useCallback, useState, useSyncExternalStore } from "react";
import { JazzContext } from "./provider.js";

export function JazzTestProvider<Acc extends Account>({
  children,
  account,
  isAuthenticated,
}: {
  children: React.ReactNode;
  account?: Acc | { guest: AnonymousJazzAgent };
  isAuthenticated?: boolean;
}) {
  const [contextManager] = useState(() => {
    return TestJazzContextManager.fromAccountOrGuest<Acc>(account, {
      isAuthenticated,
    });
  });

  return (
    <JazzContext.Provider value={contextManager}>
      {children}
    </JazzContext.Provider>
  );
}

export {
  createJazzTestAccount,
  createJazzTestGuest,
  linkAccounts,
  setActiveAccount,
  setupJazzTestSync,
  MockConnectionStatus,
} from "jazz-tools/testing";
