// packages/jazz-tools/src/solid/testing.tsx
/** @jsxImportSource solid-js */
import { Account, AnonymousJazzAgent } from "jazz-tools";
import { TestJazzContextManager } from "jazz-tools/testing";
import {
  ParentProps,
  Show,
  createEffect,
  createMemo,
  createSignal,
  onCleanup,
} from "solid-js";
import {
  JazzContext,
  type JazzContextValue,
  JazzManagerContext,
} from "./context/jazz.js";

type JazzTestProviderProps<Acc extends Account> = {
  readonly account?: Acc | { guest: AnonymousJazzAgent };
  readonly isAuthenticated?: boolean;
};

export function JazzTestProvider<Acc extends Account>(
  props: ParentProps<JazzTestProviderProps<Acc>>,
) {
  const [ctx, setCtx] = createSignal<JazzContextValue<Acc>>();

  const jazzManager = createMemo(() => {
    const account = props.account ?? (Account.getMe() as Acc);

    return TestJazzContextManager.fromAccountOrGuest<Acc>(account, {
      isAuthenticated: props.isAuthenticated,
    });
  });

  createEffect(() => {
    const unsubscribe = jazzManager().subscribe(() => {
      setCtx(jazzManager().getCurrentValue());
    });

    onCleanup(() => {
      unsubscribe();
    });
  });

  onCleanup(() => {
    jazzManager().done();
  });

  return (
    <Show when={ctx()}>
      {(jazz) => (
        <JazzContext.Provider value={jazz}>
          <JazzManagerContext.Provider value={jazzManager}>
            {props.children}
          </JazzManagerContext.Provider>
        </JazzContext.Provider>
      )}
    </Show>
  );
}

export {
  createJazzTestAccount,
  createJazzTestGuest,
  linkAccounts,
  setActiveAccount,
  setupJazzTestSync,
} from "jazz-tools/testing";

// packages/jazz-tools/src/react-core/testing.tsx
import { Account, AnonymousJazzAgent, AnyAccountSchema } from "jazz-tools";
import { TestJazzContextManager } from "jazz-tools/testing";
import { useCallback, useState, useSyncExternalStore } from "react";
import { JazzContext, JazzContextManagerContext } from "./provider.js";

export function JazzTestProvider<Acc extends Account>({
  children,
  account,
  isAuthenticated,
}: {
  children: React.ReactNode;
  account?: Acc | { guest: AnonymousJazzAgent };
  isAuthenticated?: boolean;
}) {
  const [contextManager] = useState(() => {
    return TestJazzContextManager.fromAccountOrGuest<AnyAccountSchema>(
      account,
      {
        isAuthenticated,
      },
    );
  });

  const value = useSyncExternalStore(
    useCallback((callback) => contextManager.subscribe(callback), []),
    () => contextManager.getCurrentValue(),
    () => contextManager.getCurrentValue(),
  );

  return (
    <JazzContext.Provider value={value}>
      <JazzContextManagerContext.Provider value={contextManager}>
        {children}
      </JazzContextManagerContext.Provider>
    </JazzContext.Provider>
  );
}

export {
  createJazzTestAccount,
  createJazzTestGuest,
  linkAccounts,
  setActiveAccount,
  setupJazzTestSync,
  MockConnectionStatus,
} from "jazz-tools/testing";
