// starters/nuxt-hybrid/pages/signin.vue
<template>
  <main class="page-center">
    <img src="/jazz.svg" alt="Jazz" class="wordmark" />
    <div class="card">
      <h1>Sign in</h1>
      <form @submit.prevent="handleSubmit">
        <div class="field">
          <label for="email">Email</label>
          <input id="email" v-model="email" type="email" required />
        </div>
        <div class="field">
          <label for="password">Password</label>
          <input id="password" v-model="password" type="password" required />
        </div>
        <p v-if="error" class="alert-error" role="alert">{{ error }}</p>
        <button type="submit" class="btn-primary" :disabled="isPending">
          {{ isPending ? "Signing in…" : "Sign in" }}
        </button>
      </form>
      <p class="toggle">New here? <NuxtLink to="/signup">Create an account</NuxtLink></p>
    </div>
  </main>
</template>

<script setup lang="ts">
import { ref } from "vue";

const authClient = useAuthClient();
const email = ref("");
const password = ref("");
const error = ref<string | null>(null);
const isPending = ref(false);

async function handleSubmit() {
  error.value = null;
  isPending.value = true;
  try {
    const res = await authClient.signIn.email({ email: email.value, password: password.value });
    if (res.error) {
      error.value = res.error.message ?? "Sign-in failed";
      return;
    }
    await navigateTo("/");
  } finally {
    isPending.value = false;
  }
}
</script>

// starters/sveltekit-hybrid/src/routes/signin/+page.svelte
<script lang="ts">
  import { goto } from "$app/navigation";
  import { authClient } from "$lib/auth-client";

  let error = $state<string | null>(null);

  async function handleSubmit(e: SubmitEvent) {
    e.preventDefault();
    error = null;
    const data = new FormData(e.currentTarget as HTMLFormElement);
    const email = data.get("email") as string;
    const password = data.get("password") as string;

    const res = await authClient.signIn.email({ email, password });
    if (res.error) {
      error = res.error.message ?? "Sign-in failed";
      return;
    }
    // Refresh the reactive session store so the layout observes
    // authenticated=true before we navigate — otherwise the home page
    // briefly mounts against the old anonymous Jazz client.
    await authClient.getSession();
    await goto("/");
  }
</script>

<main class="page-center">
  <img src="/jazz.svg" alt="Jazz" class="wordmark" />
  <div class="card">
    <h1>Sign in</h1>
    <form onsubmit={handleSubmit}>
      <div class="field">
        <label for="email">Email</label>
        <input id="email" name="email" type="email" required />
      </div>
      <div class="field">
        <label for="password">Password</label>
        <input id="password" name="password" type="password" required />
      </div>
      {#if error}
        <p class="alert-error" role="alert">{error}</p>
      {/if}
      <button type="submit" class="btn-primary"> Sign in </button>
    </form>
  </div>
</main>
