// homepage/homepage/content/docs/code-snippets/project-setup/app.tsx
import { createRoot } from "react-dom/client";
import { JazzReactProvider } from "jazz-tools/react";
import { MyAppAccount } from "./schema";
// [!code hide:2]
const apiKey = "";
const App = () => null;

createRoot(document.getElementById("root")!).render(
  <JazzReactProvider
    sync={{ peer: `wss://cloud.jazz.tools/?key=${apiKey}` }}
    AccountSchema={MyAppAccount}
  >
    <App />
  </JazzReactProvider>,
);

// homepage/homepage/content/docs/code-snippets/key-features/authentication/better-auth/app.svelte
<script lang="ts">
  import AuthProvider from "jazz-tools/better-auth/auth/svelte";
  import { betterAuthClient } from "./auth-client";
  import { JazzSvelteProvider } from "jazz-tools/svelte";
  import { SyncConfig } from "jazz-tools";
  const { children } = $props();
  // [!code hide]
  const apiKey = "";

  // Example configuration for authentication and peer connection
  const sync: SyncConfig = { peer: `wss://cloud.jazz.tools/?key=${apiKey}` };
</script>

<JazzSvelteProvider {sync}>
  <AuthProvider {betterAuthClient}>
    {@render children?.()}
  </AuthProvider>
</JazzSvelteProvider>
