// examples/chat-svelte/src/components/CreateChatRedirect.svelte
<script lang="ts">
  import { AccountCoState, InviteListener } from 'jazz-tools/svelte';
  import { toast } from 'svelte-sonner';
  import { Chat, ChatAccount, Message } from '@/lib/schema';
  import { navigate } from '@/lib/router';

  const account = new AccountCoState(ChatAccount, {
    resolve: { root: { chats: true } }
  });
  const me = $derived(account.current);

  let initialized = $state(false);

  new InviteListener({
    invitedObjectSchema: Chat,
    onAccept: async (chatId) => {
      const chat = await Chat.load(chatId);
      if (!chat.$isLoaded) toast.error('Failed to load chat');
      else navigate(`/chat/${chatId}`);
    }
  });

  $effect(() => {
    if (initialized || !me.$isLoaded) return;
    initialized = true;
    const chat = Chat.create([]);
    const helloMessage = Message.create(
      { text: 'Hello world', reactions: [] },
      { owner: chat.$jazz.owner }
    );
    chat.$jazz.push(helloMessage);
    me.root.chats.$jazz.set(chat.$jazz.id, chat);
    navigate(`/#/chat/${chat.$jazz.id}`);
  });
</script>

<div class="flex-1 overflow-y-auto flex flex-col-reverse">
  <article>Creating chat...</article>
</div>

// examples/chat-reatom-react/src/components/CreateChatRedirect.tsx
import { useEffect, useRef } from "react";
import { reatomComponent } from "@reatom/react";
import { wrap } from "@reatom/core";
import type { DurabilityTier } from "jazz-tools";
import { jazz } from "@/jazz";
import { myProfile } from "@/model/my-profile";
import { chatRoute } from "@/routes";
import { app } from "../../schema.js";

export const CreateChatRedirect = reatomComponent(() => {
  const { db, session } = jazz();
  const profile = myProfile();
  const initialized = useRef(false);
  const userId = session?.user_id ?? null;
  const sharedWriteOptions: { tier: DurabilityTier } = {
    tier: db.getConfig().serverUrl ? "edge" : "local",
  };

  useEffect(() => {
    if (initialized.current || !userId || !profile) return;
    initialized.current = true;

    void (async () => {
      const chat = await wrap(
        db
          .insert(app.chats, {
            isPublic: true,
            createdBy: userId,
          })
          .wait(sharedWriteOptions),
      );

      await wrap(db.insert(app.chatMembers, { chatId: chat.id, userId }).wait(sharedWriteOptions));

      await wrap(
        db
          .insert(app.messages, {
            chatId: chat.id,
            text: "Hello world",
            senderId: profile.id,
            createdAt: new Date(),
          })
          .wait(sharedWriteOptions),
      );

      chatRoute.go({ chatId: chat.id });
    })().catch((error) => {
      console.error("failed to create initial chat", error);
      initialized.current = false;
    });
  }, [db, userId, profile, sharedWriteOptions]);

  return (
    <div className="flex-1 overflow-y-auto flex flex-col-reverse">
      <article>Creating chat...</article>
    </div>
  );
}, "CreateChatRedirect");
