// examples/docs/todo-client-localfirst-solid/src/AuthOffline.tsx
import { type ParentProps } from "solid-js";
import type { DbConfig } from "jazz-tools";
import { JazzProvider } from "jazz-tools/solid";

// Prepare a handle outside this context with createAccountManager.
export function AuthOffline(props: ParentProps<{ config: DbConfig }>) {
  return (
    <JazzProvider config={{ ...props.config, serverUrl: undefined }} fallback={<p>Loading...</p>}>
      {props.children}
    </JazzProvider>
  );
}

// examples/docs/todo-client-localfirst-vue/src/AuthOffline.vue
<script setup lang="ts">
import type { DbConfig } from "jazz-tools";
import { JazzProvider } from "jazz-tools/vue";
// Prepare a handle outside this context with createAccountManager.
defineProps<{ config: DbConfig }>();
</script>
<template>
  <JazzProvider :config="{ ...config, serverUrl: undefined }"><slot /></JazzProvider>
</template>
