// examples/docs/todo-client-localfirst-svelte/src/AuthDemo.svelte
<!-- #region auth-demo-svelte -->
<script lang="ts">
  import {
    createJazzClient,
    JazzSvelteProvider,
    SyntheticUserSwitcher,
    getActiveSyntheticAuth,
  } from 'jazz-tools/svelte';

  const appId = 'my-app';
  const active = getActiveSyntheticAuth(appId, { defaultMode: 'demo' });

  const client = createJazzClient({
    appId,
    serverUrl: 'http://127.0.0.1:4200',
    localAuthMode: active.localAuthMode,
    localAuthToken: active.localAuthToken,
  });
</script>

<SyntheticUserSwitcher {appId} defaultMode="demo" />
<JazzSvelteProvider {client}>
  {#snippet children({ db })}
    <slot />
  {/snippet}
</JazzSvelteProvider>
<!-- #endregion auth-demo-svelte -->

// examples/docs/todo-client-localfirst-vue/src/AuthDemo.vue
<script setup lang="ts">
import {
  createJazzClient,
  getActiveSyntheticAuth,
  JazzProvider,
  SyntheticUserSwitcher,
} from "jazz-tools/vue";

const appId = "my-app";
const active = getActiveSyntheticAuth(appId, { defaultMode: "demo" });

const client = createJazzClient({
  appId,
  serverUrl: "http://127.0.0.1:4200",
  localAuthMode: active.localAuthMode,
  localAuthToken: active.localAuthToken,
});
</script>

<template>
  <SyntheticUserSwitcher :app-id="appId" default-mode="demo" />
  <JazzProvider :client="client">
    <slot />
  </JazzProvider>
</template>
