// examples/docs/todo-client-localfirst-solid/src/AuthSessionExamples.tsx
import { createMemo } from "solid-js";
import { useAll, useDb, useSession } from "jazz-tools/solid";
import { app } from "../session-app.js";

export function AuthSessionExamples() {
  const db = useDb();
  const session = useSession();
  const sessionUserId = createMemo(() => session()?.user_id ?? null);
  const ownedTodos = useAll(() => ({
    query: sessionUserId() ? app.todos.where({ owner_id: sessionUserId()! }) : undefined,
  }));

  function addOwnedTodo(title: string) {
    const ownerId = sessionUserId();
    if (!ownerId) return;
    db().insert(app.todos, { title, done: false, owner_id: ownerId });
  }

  void ownedTodos;
  void addOwnedTodo;
  return null;
}

// examples/docs/todo-client-localfirst-vue/src/AuthSessionExamples.vue
<script setup lang="ts">
import { useAll, useDb, useSession } from "jazz-tools/vue";
import { app } from "../session-app.js";

const db = useDb();

// #region auth-session-vue-hook
const session = useSession();
// #endregion auth-session-vue-hook

// #region auth-session-vue-user-id
const sessionUserId = session?.user_id ?? null;
// #endregion auth-session-vue-user-id

// #region auth-session-vue-query
const { data: ownedTodos } = useAll(
  sessionUserId ? app.todos.where({ owner_id: sessionUserId }) : undefined,
);
// #endregion auth-session-vue-query

// #region auth-session-vue-insert
function addOwnedTodo(title: string) {
  if (!sessionUserId) return;

  db.insert(app.todos, {
    title,
    done: false,
    owner_id: sessionUserId,
  });
}
// #endregion auth-session-vue-insert

void ownedTodos;
void addOwnedTodo;
</script>

<template></template>
