// examples/docs/todo-client-localfirst-svelte/src/AuthAnonymous.svelte
<!-- #region auth-anon-svelte -->
<script lang="ts">
  import type { Db } from 'jazz-tools';
  import { createJazzClient, JazzSvelteProvider } from 'jazz-tools/svelte';

  const client = createJazzClient({
    appId: 'my-app',
    serverUrl: 'http://127.0.0.1:4200',
  });
</script>

<JazzSvelteProvider {client}>
  {#snippet children({ db }: { db: Db })}
    <slot />
  {/snippet}
</JazzSvelteProvider>
<!-- #endregion auth-anon-svelte -->

// examples/docs/todo-client-localfirst-vue/src/AuthAnonymous.vue
<script setup lang="ts">
import { createJazzClient, JazzProvider } from "jazz-tools/vue";

const client = createJazzClient({
  asyncSubscriptionsOnly: false,
  appId: "my-app",
  serverUrl: "http://127.0.0.1:4200",
});
</script>

<template>
  <JazzProvider :client="client">
    <slot />
  </JazzProvider>
</template>
