// examples/docs/todo-client-localfirst-svelte/src/AuthLocalfirst.svelte
<!-- #region auth-localfirst-svelte -->
<script lang="ts">
  import { onMount } from 'svelte';
  import { BrowserAuthSecretStore, createJazzClient, JazzSvelteProvider } from 'jazz-tools/svelte';

  let client = $state<ReturnType<typeof createJazzClient> | null>(null);

  onMount(async () => {
    const secret = await BrowserAuthSecretStore.getOrCreateSecret();
    client = createJazzClient({
      appId: 'my-app',
      secret,
    });
  });
</script>

{#if client}
  <JazzSvelteProvider {client}>
    {#snippet children({ db })}
      <slot />
    {/snippet}
  </JazzSvelteProvider>
{/if}
<!-- #endregion auth-localfirst-svelte -->

// examples/docs/todo-client-localfirst-vue/src/AuthLocalfirst.vue
<script setup lang="ts">
import { ref, onMounted } from "vue";
import { createJazzClient, JazzProvider } from "jazz-tools/vue";
import { BrowserAuthSecretStore } from "jazz-tools";

const client = ref<ReturnType<typeof createJazzClient> | null>(null);

onMounted(async () => {
  const secret = await BrowserAuthSecretStore.getOrCreateSecret();
  client.value = createJazzClient({
    appId: "my-app",
    secret,
  });
});
</script>

<template>
  <JazzProvider v-if="client" :client="client">
    <slot />
  </JazzProvider>
</template>
