// examples/docs/todo-client-localfirst-solid/src/BranchExample.tsx
import { type ParentProps } from "solid-js";
import { JazzProvider, createSolidJazzClient } from "jazz-tools/solid";

export function BranchExample(props: ParentProps) {
  const client = createSolidJazzClient(() => ({
    appId: "my-app", // Register for an app ID free at v2.dashboard.jazz.tools
    env: "prod",
    userBranch: "staging",
  }));
  return <JazzProvider client={client}>{props.children}</JazzProvider>;
}

// examples/docs/todo-client-localfirst-vue/src/BranchExample.vue
<script setup lang="ts">
// #region branch-vue
import { createJazzClient, JazzProvider } from "jazz-tools/vue";

const client = createJazzClient({
  appId: "my-app", // Register for an app ID free at v2.dashboard.jazz.tools
  env: "prod",
  userBranch: "staging",
});
// #endregion branch-vue
</script>

<template>
  <JazzProvider :client="client">
    <slot />
  </JazzProvider>
</template>
