// examples/docs/todo-client-localfirst-svelte/src/BranchExample.svelte
<script lang="ts">
  // #region branch-svelte
  import { createJazzClient, JazzSvelteProvider } from 'jazz-tools/svelte';

  const client = createJazzClient({
    appId: 'my-app', // Register for an app ID free at v2.dashboard.jazz.tools
    env: 'prod',
    userBranch: 'staging',
  });
  // #endregion branch-svelte
</script>

<JazzSvelteProvider {client}>
  <slot />
</JazzSvelteProvider>

// examples/docs/todo-client-localfirst-vue/src/BranchExample.vue
<script setup lang="ts">
// #region branch-vue
import { createJazzClient, JazzProvider } from "jazz-tools/vue";

const client = createJazzClient({
  appId: "my-app", // Register for an app ID free at v2.dashboard.jazz.tools
  env: "prod",
  userBranch: "staging",
});
// #endregion branch-vue
</script>

<template>
  <JazzProvider :client="client">
    <slot />
  </JazzProvider>
</template>
