// examples/docs/todo-client-localfirst-solid/src/ConditionalQueryExample.tsx
import { For, Show, createMemo, createSignal } from "solid-js";
import { useAll } from "jazz-tools/solid";
import { app } from "../schema.js";

export function ConditionalQueryExample() {
  const [filter, setFilter] = createSignal<string | null>(null);
  const query = createMemo(() =>
    filter() ? app.todos.where({ title: { contains: filter()! } }) : undefined,
  );
  const filtered = useAll(() => ({ query: query() }));

  return (
    <>
      <input
        value={filter() ?? ""}
        onInput={(e) => setFilter(e.currentTarget.value || null)}
        placeholder="Filter by title"
      />
      <Show when={filtered.data}>
        <ul>
          <For each={filtered.data ?? []}>{(todo) => <li>{todo.title}</li>}</For>
        </ul>
      </Show>
    </>
  );
}

// examples/docs/todo-client-localfirst-vue/src/ConditionalQueryExample.vue
<!-- #region reading-conditional-query-vue -->
<script setup lang="ts">
import { ref, computed } from "vue";
import { useAll } from "jazz-tools/vue";
import { app } from "../schema.js";

const filter = ref<string | null>(null);
const query = computed(() =>
  filter.value ? app.todos.where({ title: { contains: filter.value } }) : undefined,
);
const { data: filtered } = useAll(query);
</script>

<template>
  <input v-model="filter" placeholder="Filter by title" />
  <ul v-if="filtered">
    <li v-for="todo in filtered" :key="todo.id">{{ todo.title }}</li>
  </ul>
</template>
<!-- #endregion reading-conditional-query-vue -->
