// examples/docs/todo-client-localfirst-expo/src/ConditionalQueryExample.tsx
import { useState } from "react";
import { Text, TextInput, View } from "react-native";
import { useAll } from "jazz-tools/react-native";
import { app } from "../schema";

// #region reading-conditional-query-expo
export function FilteredTodos() {
  const [filter, setFilter] = useState<string | null>(null);
  const { data: filtered } = useAll(
    filter ? app.todos.where({ title: { contains: filter } }) : undefined,
  );

  return (
    <View>
      <TextInput
        value={filter ?? ""}
        onChangeText={(v) => setFilter(v || null)}
        placeholder="Filter by title"
      />
      {filtered?.map((todo) => (
        <Text key={todo.id}>{todo.title}</Text>
      ))}
    </View>
  );
}
// #endregion reading-conditional-query-expo

// examples/docs/todo-client-localfirst-vue/src/ConditionalQueryExample.vue
<!-- #region reading-conditional-query-vue -->
<script setup lang="ts">
import { ref, computed } from "vue";
import { useAll } from "jazz-tools/vue";
import { app } from "../schema.js";

const filter = ref<string | null>(null);
const query = computed(() =>
  filter.value ? app.todos.where({ title: { contains: filter.value } }) : undefined,
);
const { data: filtered } = useAll(query);
</script>

<template>
  <input v-model="filter" placeholder="Filter by title" />
  <ul v-if="filtered">
    <li v-for="todo in filtered" :key="todo.id">{{ todo.title }}</li>
  </ul>
</template>
<!-- #endregion reading-conditional-query-vue -->
