// examples/docs/todo-client-localfirst-svelte/src/DbSessionExamples.svelte
<script lang="ts">
  import { getDb, getSession } from 'jazz-tools/svelte';
  import { app } from '../schema.js';

  // #region db-access-svelte
  // Callable anywhere — component, store, or utility module
  const db = getDb();

  async function addTodo(title: string) {
    await db.insert(app.todos, { title, done: false });
  }
  // #endregion db-access-svelte

  // #region session-svelte
  const session = getSession(); // { user_id: string } | null
  // #endregion session-svelte

  void addTodo;
  void session;
</script>

// examples/docs/todo-client-localfirst-vue/src/DbSessionExamples.vue
<script setup lang="ts">
  import { useDb, useSession } from "jazz-tools/vue";
  import { app } from "../schema/app.js";

  // #region db-access-vue
  // Must be called inside setup() or <script setup>
  const db = useDb();

  async function addTodo(title: string) {
    await db.insert(app.todos, { title, done: false });
  }
  // #endregion db-access-vue

  // #region session-vue
  const session = useSession(); // ShallowRef<{ user_id: string } | null>
  // #endregion session-vue

  void addTodo;
  void session;
</script>

<template></template>
