// examples/docs/todo-client-localfirst-solid/src/LiveQueryExample.tsx
import { For, Show } from "solid-js";
import { useAll } from "jazz-tools/solid";
import { app } from "../schema.js";

export function LiveQueryExample() {
  const todos = useAll(() => ({ query: app.todos }));
  return (
    <Show when={todos.data !== undefined} fallback={<p>Connecting...</p>}>
      <ul>
        <For each={todos.data ?? []}>{(todo) => <li>{todo.title}</li>}</For>
      </ul>
    </Show>
  );
}

// examples/docs/todo-client-localfirst-vue/src/LiveQueryExample.vue
<!-- #region reading-loading-state-vue -->
<script setup lang="ts">
import { useAll } from "jazz-tools/vue";
import { app } from "../schema.js";

const { data: todos } = useAll(app.todos);
// undefined = not yet connected; [] = connected, no rows; [...] = rows present
</script>

<template>
  <p v-if="todos === undefined">Connecting…</p>
  <ul v-else>
    <li v-for="todo in todos" :key="todo.id">{{ todo.title }}</li>
  </ul>
</template>
<!-- #endregion reading-loading-state-vue -->
