// examples/docs/todo-client-localfirst-svelte/src/ProviderExample.svelte
<!-- #region provider-svelte -->
<script lang="ts">
  import type { Snippet } from "svelte";
  import type { DbConfig } from "jazz-tools";
  import { JazzSvelteProvider } from "jazz-tools/svelte";
  // Prepare a handle outside this context with createAccountManager.
  let { config, children }: { config: DbConfig; children: Snippet } = $props();
</script>
<JazzSvelteProvider {config}>{@render children()}</JazzSvelteProvider>
<!-- #endregion provider-svelte -->

// examples/docs/todo-client-localfirst-vue/src/ProviderExample.vue
<script setup lang="ts">
import type { DbConfig } from "jazz-tools";
import { JazzProvider } from "jazz-tools/vue";
// Prepare a handle outside this context with createAccountManager.
defineProps<{ config: DbConfig }>();
</script>
<template>
  <JazzProvider :config="config"><slot /></JazzProvider>
</template>
