// examples/docs/todo-client-localfirst-solid/src/QuerySubscriptionExample.tsx
import { For } from "solid-js";
import { useAll } from "jazz-tools/solid";
import { app } from "../schema.js";

export function QuerySubscriptionExample() {
  const todos = useAll(() => ({ query: app.todos.where({ done: false }) }));
  return <For each={todos.data ?? []}>{(todo) => <li>{todo.title}</li>}</For>;
}

// examples/docs/todo-client-localfirst-vue/src/QuerySubscriptionExample.vue
<!-- #region query-subscription-vue -->
<script setup lang="ts">
import { useAll } from "jazz-tools/vue";
import { app } from "../schema.js";

const { data: todos } = useAll(app.todos.where({ done: false }));
</script>

<template>
  <li v-for="todo in todos ?? []" :key="todo.id">{{ todo.title }}</li>
</template>
<!-- #endregion query-subscription-vue -->
