// examples/docs/todo-client-localfirst-expo/src/quickstart-list.tsx
import { FlatList, View } from "react-native";
import { useAll } from "jazz-tools/react";
import { app } from "../schema";
import { TodoItem } from "./TodoItem";
import { AddTodo } from "./AddTodo";

export function TodoList() {
  const todos = useAll(app.todos) ?? [];

  return (
    <View style={{ flex: 1, gap: 12 }}>
      <FlatList
        data={todos}
        keyExtractor={(item) => item.id}
        renderItem={({ item }) => <TodoItem id={item.id} />}
      />
      <AddTodo />
    </View>
  );
}

// examples/docs/todo-client-localfirst-vue/src/quickstart-list.vue
<script setup lang="ts">
import { useAll } from "jazz-tools/vue";
import { app } from "../schema.js";
import TodoItem from "./TodoItem.vue";
import AddTodo from "./AddTodo.vue";

const { data: todos } = useAll(app.todos);
</script>

<template>
  <ul>
    <TodoItem v-for="todo in todos ?? []" :key="todo.id" :id="todo.id" />
  </ul>
  <AddTodo />
</template>
