// examples/docs/todo-client-localfirst-svelte/src/RuntimeConfigExample.svelte
<!-- #region context-setup-svelte-runtime-sources -->
<script lang="ts">
  import { JazzProvider, createJazzClient } from "jazz-tools/svelte";

  const client = createJazzClient({
    appId: "my-app", // Register for an app ID free at v2.dashboard.jazz.tools
    serverUrl: "https://my-jazz-server.example.com",
    runtimeSources: {
      baseUrl: "/assets/jazz/",
    },
  });
</script>

<JazzProvider {client}>
  <!-- ... -->
</JazzProvider>
<!-- #endregion context-setup-svelte-runtime-sources -->

// examples/docs/todo-client-localfirst-vue/src/RuntimeConfigExample.vue
<!-- #region context-setup-vue-runtime-sources -->
<script setup lang="ts">
import { createJazzClient, JazzProvider } from "jazz-tools/vue";

const client = createJazzClient({
  appId: "my-app", // Register for an app ID free at v2.dashboard.jazz.tools
  serverUrl: "https://my-jazz-server.example.com",
  runtimeSources: {
    baseUrl: "/assets/jazz/",
  },
});
</script>

<template>
  <JazzProvider :client="client">
    <!-- ... -->
  </JazzProvider>
</template>
<!-- #endregion context-setup-vue-runtime-sources -->
