// examples/docs/todo-client-localfirst-svelte/src/TodoList.svelte
<!-- #region read-write-svelte -->
<script lang="ts">
  // #region reading-reactive-svelte
  import { getDb, QuerySubscription } from 'jazz-tools/svelte';
  import { app } from '../schema/app.js';

  const db = getDb();
  const todos = new QuerySubscription(app.todos);
  // #endregion reading-reactive-svelte

  // #region filtering-svelte
  const incompleteTodos = new QuerySubscription(
    app.todos.where({ done: false }).orderBy('title', 'asc').limit(50),
  );
  // #endregion filtering-svelte

  // #region reading-tier-svelte
  const todosAtEdgeDurability = new QuerySubscription(app.todos, { tier: 'edge' });
  // #endregion reading-tier-svelte

  let title = $state('');

  // #region writing-use-db-svelte
  function handleSubmit(e: SubmitEvent) {
    e.preventDefault();
    if (!title.trim()) return;
    // #region writing-insert-svelte
    db.insert(app.todos, { title: title.trim(), done: false });
    // #endregion writing-insert-svelte
    title = '';
  }

  // #region writing-mutations-svelte
  function toggleTodo(todo: { id: string; done: boolean }) {
    db.update(app.todos, todo.id, { done: !todo.done });
  }

  function removeTodo(id: string) {
    db.delete(app.todos, id);
  }
  // #endregion writing-mutations-svelte
  // #endregion writing-use-db-svelte

  // #region writing-durability-svelte
  async function addImportantTodo(todoTitle: string) {
    const { id } = await db.insertDurable(app.todos, { title: todoTitle, done: false }, { tier: 'edge' });
    await db.updateDurable(app.todos, id, { done: true }, { tier: 'edge' });
    await db.deleteDurable(app.todos, id, { tier: 'global' });
  }
  // #endregion writing-durability-svelte
</script>

<form onsubmit={handleSubmit}>
  <input type="text" bind:value={title} placeholder="What needs to be done?" required />
  <button type="submit">Add</button>
</form>
<!-- #region render-list-svelte -->
<ul id="todo-list">
  {#each todos.current ?? [] as todo (todo.id)}
    <li class={todo.done ? 'done' : ''}>
      <input
        type="checkbox"
        checked={todo.done}
        onchange={() => toggleTodo(todo)}
        class="toggle"
      />
      <span>{todo.title}</span>
      {#if todo.description}
        <small>{todo.description}</small>
      {/if}
      <button class="delete-btn" onclick={() => removeTodo(todo.id)}>
        &times;
      </button>
    </li>
  {/each}
</ul>
<!-- #endregion render-list-svelte -->
<!-- #endregion read-write-svelte -->

// examples/docs/todo-client-localfirst-vue/src/TodoList.vue
<script setup lang="ts">
import { ref } from "vue";
import { useAll, useDb } from "jazz-tools/vue";
import { app } from "../schema/app.js";

// #region reading-reactive-hooks-vue
const db = useDb();
const todos = useAll(app.todos);
// #endregion reading-reactive-hooks-vue

// #region reading-filtering-vue
const incompleteTodos = useAll(app.todos.where({ done: false }).orderBy("title", "asc").limit(50));
// #endregion reading-filtering-vue

// #region writing-use-db-vue
function addTodo(todoTitle: string) {
  db.insert(app.todos, { title: todoTitle, done: false });
}

function toggleTodo(todo: { id: string; done: boolean }) {
  db.update(app.todos, todo.id, { done: !todo.done });
}

function removeTodo(id: string) {
  db.delete(app.todos, id);
}
// #endregion writing-use-db-vue

// #region writing-durability-vue
async function addImportantTodo(todoTitle: string) {
  const { id } = await db.insertDurable(
    app.todos,
    { title: todoTitle, done: false },
    { tier: "edge" },
  );
  await db.updateDurable(app.todos, id, { done: true }, { tier: "edge" });
  await db.deleteDurable(app.todos, id, { tier: "global" });
}
// #endregion writing-durability-vue

const title = ref("");

function handleSubmit(event: SubmitEvent) {
  event.preventDefault();
  if (!title.value.trim()) {
    return;
  }

  addTodo(title.value.trim());
  title.value = "";
}
</script>

<template>
  <form @submit="handleSubmit">
    <input v-model="title" type="text" placeholder="What needs to be done?" required />
    <button type="submit">Add</button>
  </form>

  <ul id="todo-list">
    <li v-for="todo in todos ?? []" :key="todo.id" :class="{ done: todo.done }">
      <input type="checkbox" :checked="todo.done" class="toggle" @change="toggleTodo(todo)" />
      <span>{{ todo.title }}</span>
      <small v-if="todo.description">{{ todo.description }}</small>
      <button class="delete-btn" type="button" @click="removeTodo(todo.id)">&times;</button>
    </li>
  </ul>
</template>
