// examples/todo-client-localfirst-solid/src/App.tsx
import { Show, type JSX } from "solid-js";
import { JazzProvider, useLocalFirstAuth } from "jazz-tools/solid";
import type { DbConfig } from "jazz-tools";
import { Toaster } from "solid-sonner";
import { TodoList } from "./TodoList.js";

type AppProps = {
  config?: Partial<DbConfig>;
  fallback?: JSX.Element;
};

function readEnv(name: string): string | undefined {
  return (import.meta as ImportMeta & { env?: Record<string, string | undefined> }).env?.[name];
}

function defaultConfig(secret: string, overrides: Partial<DbConfig> = {}): DbConfig {
  const appId = overrides.appId ?? readEnv("VITE_JAZZ_APP_ID");
  const serverUrl = overrides.serverUrl ?? readEnv("VITE_JAZZ_SERVER_URL");

  if (!appId) {
    throw new Error("Missing appId: add jazzPlugin() to vite.config.ts or set VITE_JAZZ_APP_ID");
  }

  return {
    appId,
    env: "dev",
    userBranch: "main",
    secret,
    ...(serverUrl ? { serverUrl } : {}),
    ...overrides,
  };
}

function ReadyApp(props: { secret: string; config?: Partial<DbConfig>; fallback?: JSX.Element }) {
  const resolvedConfig = () => defaultConfig(props.secret, props.config ?? {});

  return (
    <JazzProvider config={resolvedConfig()} fallback={props.fallback ?? <p>Loading...</p>}>
      <h1>Todos</h1>
      <TodoList />
      <Toaster />
    </JazzProvider>
  );
}

export function App(props: AppProps = {}) {
  const auth = useLocalFirstAuth();

  return (
    <Show when={!auth.isLoading && auth.secret} fallback={props.fallback ?? <p>Loading...</p>}>
      {(secret) => <ReadyApp secret={secret()} config={props.config} fallback={props.fallback} />}
    </Show>
  );
}

// examples/todo-client-localfirst-vue/src/App.vue
<script setup lang="ts">
import { computed } from "vue";
import { JazzProvider } from "jazz-tools/vue";
import { generateAuthSecret, type DbConfig } from "jazz-tools";
import { Toaster } from "vue-sonner";
import TodoList from "./TodoList.vue";

interface Props {
  config?: Partial<DbConfig>;
}

const props = withDefaults(defineProps<Props>(), {
  config: () => ({}),
});

function readEnv(name: string): string | undefined {
  return (import.meta as ImportMeta & { env?: Record<string, string | undefined> }).env?.[name];
}

function secretStorageKey(appId: string): string {
  return `jazz-auth-secret:${encodeURIComponent(appId)}`;
}

function getOrCreateSecretSync(appId: string): string {
  const stored = localStorage.getItem(secretStorageKey(appId));
  if (stored) return stored;
  const secret = generateAuthSecret();
  localStorage.setItem(secretStorageKey(appId), secret);
  return secret;
}

// #region context-setup-vue
function defaultConfig(overrides: Partial<DbConfig> = {}): DbConfig {
  const appId = overrides.appId ?? readEnv("VITE_JAZZ_APP_ID");
  const serverUrl = overrides.serverUrl ?? readEnv("VITE_JAZZ_SERVER_URL");
  if (!appId)
    throw new Error("Missing appId: add jazzPlugin() to vite.config.ts or set VITE_JAZZ_APP_ID");
  const secret = overrides.secret ?? getOrCreateSecretSync(appId);

  return {
    appId,
    env: "dev",
    userBranch: "main",
    secret,
    ...(serverUrl ? { serverUrl } : {}),
    ...overrides,
  };
}
// #endregion context-setup-vue

const config = computed(() => defaultConfig(props.config));
</script>

<template>
  <JazzProvider :config="config">
    <h1>Todos</h1>
    <TodoList />
    <Toaster />
    <template #fallback>
      <p>Loading...</p>
    </template>
  </JazzProvider>
</template>
