// packages/jazz-tools/src/solid/auth/PassphraseAuth.tsx
import { PassphraseAuth } from "jazz-tools";
import { createEffect, createMemo, createSignal, onCleanup } from "solid-js";
import { useAuthSecretStorage, useJazzContext } from "../jazz.js";
import { useIsAuthenticated } from "./useIsAuthenticated.js";

/** @category Auth Providers */
export function usePassphraseAuth({
  wordlist,
}: {
  wordlist: string[];
}) {
  const jazz = useJazzContext();
  const authSecretStorage = useAuthSecretStorage();
  const isAuthenticated = useIsAuthenticated();

  const state = () => (isAuthenticated() ? "signedIn" : "anonymous");

  const auth = createMemo(() => {
    const pAuth = new PassphraseAuth(
      jazz().node.crypto,
      jazz().authenticate,
      jazz().register,
      authSecretStorage(),
      wordlist,
    );

    void pAuth.loadCurrentAccountPassphrase();

    return pAuth;
  });

  const [passphrase, setPassphrase] = createSignal(auth().passphrase);

  createEffect(() => {
    const off = auth().subscribe(() => {
      setPassphrase(auth().passphrase);
    });

    onCleanup(() => {
      off();
    });
  });

  return {
    logIn: auth().logIn,
    signUp: auth().signUp,
    registerNewAccount: auth().registerNewAccount,
    generateRandomPassphrase: auth().generateRandomPassphrase,
    passphrase,
    state,
  };
}

// packages/jazz-tools/src/react-core/auth/PassphraseAuth.tsx
import { PassphraseAuth } from "jazz-tools";
import { useCallback, useMemo, useSyncExternalStore } from "react";
import { useAuthSecretStorage, useJazzContextValue } from "../hooks.js";
import { useIsAuthenticated } from "../hooks.js";

/**
 * `usePassphraseAuth` hook provides a `JazzAuth` object for passphrase authentication.
 *
 * @example
 * ```ts
 * const auth = usePassphraseAuth({ appName, appHostname, wordlist });
 * ```
 *
 * @category Auth Providers
 */
export function usePassphraseAuth({ wordlist }: { wordlist: string[] }) {
  const context = useJazzContextValue();
  const authSecretStorage = useAuthSecretStorage();

  if ("guest" in context) {
    throw new Error("Passphrase auth is not supported in guest mode");
  }

  const authMethod = useMemo(() => {
    return new PassphraseAuth(
      context.node.crypto,
      context.authenticate,
      context.register,
      authSecretStorage,
      wordlist,
    );
  }, [wordlist]);

  const passphrase = useSyncExternalStore(
    useCallback(
      (callback) => {
        authMethod.loadCurrentAccountPassphrase();
        return authMethod.subscribe(callback);
      },
      [authMethod],
    ),
    () => authMethod.passphrase,
  );

  const isAuthenticated = useIsAuthenticated();
  return {
    state: isAuthenticated ? "signedIn" : "anonymous",
    logIn: authMethod.logIn,
    signUp: authMethod.signUp,
    registerNewAccount: authMethod.registerNewAccount,
    generateRandomPassphrase: authMethod.generateRandomPassphrase,
    passphrase,
  } as const;
}
