// packages/jazz-tools/src/svelte/Provider.svelte
<script
  lang="ts"
  generics="S extends (AccountClass<Account> & CoValueFromRaw<Account>) | AnyAccountSchema"
>
  import type { AuthSecretStorage, InstanceOfSchema } from "jazz-tools";
  import {
    Account,
    type AccountClass,
    type AnyAccountSchema,
    type CoValueFromRaw,
  } from "jazz-tools";
  import {
    JazzBrowserContextManager,
    type JazzContextManagerProps,
  } from "jazz-tools/browser";
  import { type Snippet, setContext, untrack } from "svelte";
  import { JAZZ_AUTH_CTX, JAZZ_CTX, type JazzContext } from "./jazz.svelte.js";

  let props: JazzContextManagerProps<S> & {
    children?: Snippet;
    enableSSR?: boolean;
    authSecretStorageKey?: string;
    navigation?: {
      beforeNavigate: (
        callback: (navigation: any) => void | Promise<void>,
      ) => void;
      goto: (url: string, opts?: any) => Promise<void>;
    };
  } = $props();

  const contextManager = new JazzBrowserContextManager<S>({
    useAnonymousFallback: props.enableSSR,
    authSecretStorageKey: props.authSecretStorageKey,
  });

  const ctx = $state<JazzContext<InstanceOfSchema<S>>>({ current: undefined });

  setContext<JazzContext<InstanceOfSchema<S>>>(JAZZ_CTX, ctx);
  setContext<AuthSecretStorage>(
    JAZZ_AUTH_CTX,
    contextManager.getAuthSecretStorage(),
  );

  if (props.navigation) {
    let isReplaying = false;

    props.navigation.beforeNavigate(async (navigation: any) => {
      if (isReplaying || navigation.willUnload) return;

      const current = ctx.current;
      if (!current) return;

      if (current.node.syncManager.unsyncedTracker.isAllSynced()) return;

      navigation.cancel();

      try {
        await current.node.syncManager.waitForAllCoValuesSync(3000);
      } catch {}

      if (navigation.to?.url) {
        isReplaying = true;
        try {
          const url = navigation.to.url;
          await props.navigation!.goto(
            url.pathname + url.search + url.hash,
          );
        } finally {
          isReplaying = false;
        }
      }
    });
  }

  $effect(() => {
    props.sync.when;
    props.sync.peer;
    props.storage;
    props.guestMode;
    return untrack(() => {
      if (!props.sync) return;

      contextManager
        .createContext({
          sync: props.sync,
          storage: props.storage,
          guestMode: props.guestMode,
          AccountSchema: props.AccountSchema,
          defaultProfileName: props.defaultProfileName,
          onAnonymousAccountDiscarded: props.onAnonymousAccountDiscarded,
          onLogOut: props.onLogOut,
        })
        .catch((error) => {
          console.error("Error creating Jazz browser context:", error);
        });
    });
  });

  $effect(() => {
    return contextManager.subscribe(() => {
      ctx.current = contextManager.getCurrentValue();
    });
  });
</script>

{#if ctx.current}
  {@render props.children?.()}
{/if}

// packages/jazz-tools/src/solid/context/Provider.tsx
/**
 * @jsxImportSource solid-js
 */
import type { InstanceOfSchema } from "jazz-tools";
import {
  Account,
  type AccountClass,
  type AnyAccountSchema,
  type CoValueFromRaw,
} from "jazz-tools";
import {
  JazzBrowserContextManager,
  type JazzContextManagerProps,
} from "jazz-tools/browser";
import {
  type ParentProps,
  Show,
  createEffect,
  createMemo,
  createSignal,
  onCleanup,
} from "solid-js";
import {
  JazzContext,
  type JazzContextValue,
  JazzManagerContext,
} from "./jazz.js";

type JazzAccount = AccountClass<Account> & CoValueFromRaw<Account>;

export type JazzProviderProps<S extends JazzAccount | AnyAccountSchema> = {
  readonly enableSSR?: boolean;
} & JazzContextManagerProps<S>;

export const JazzProvider = <S extends JazzAccount | AnyAccountSchema>(
  props: ParentProps<JazzProviderProps<S>>,
) => {
  const jazzManager = createMemo(
    () =>
      new JazzBrowserContextManager<S>({
        useAnonymousFallback: props.enableSSR,
      }),
  );

  const [ctx, setCtx] = createSignal<JazzContextValue<InstanceOfSchema<S>>>();

  createEffect(() => {
    jazzManager()
      .createContext({
        sync: props.sync,
        storage: props.storage,
        guestMode: props.guestMode,
        AccountSchema: props.AccountSchema,
        defaultProfileName: props.defaultProfileName,
        onAnonymousAccountDiscarded: props.onAnonymousAccountDiscarded,
        onLogOut: props.onLogOut,
        logOutReplacement: props.logOutReplacement,
      })
      .catch((error) => {
        console.error("Error creating Jazz browser context:", error);
      });
  });

  const authStorage = () => jazzManager().getAuthSecretStorage();

  createEffect(() => {
    const unsubscribe = jazzManager().subscribe(() => {
      setCtx(jazzManager().getCurrentValue());
    });

    onCleanup(() => {
      unsubscribe();
    });
  });

  onCleanup(() => {
    jazzManager().done();
  });

  return (
    <Show when={ctx()}>
      {(ctxValue) => {
        return (
          <JazzContext.Provider value={ctxValue}>
            <JazzManagerContext.Provider value={jazzManager}>
              {props.children}
            </JazzManagerContext.Provider>
          </JazzContext.Provider>
        );
      }}
    </Show>
  );
};
