// examples/chat-svelte/src/components/editor/FloatingToolbar.svelte
<script lang="ts">
  import type { EditorView } from 'prosemirror-view';
  import { toggleMark } from 'prosemirror-commands';
  import { Button } from '@/components/ui/button';
  import { ButtonGroup } from '@/components/ui/button-group';
  import { type MenuState, TOOLBAR_BUTTONS } from './utils';

  interface Props {
    view: EditorView | null;
    menuState: MenuState;
  }

  let { view, menuState }: Props = $props();

  function handleToggle(markName: string) {
    if (!view) return;
    const mark = view.state.schema.marks[markName];
    if (mark) {
      toggleMark(mark)(view.state, view.dispatch);
      view.focus();
    }
  }
</script>

{#if menuState.show && view}
  <div
    tabindex={0}
    role="toolbar"
    style:position="fixed"
    style:top="{menuState.top}px"
    style:left="{menuState.left}px"
    style:transform="translateX(-50%)"
    class="z-50 rounded-sm border bg-background shadow-md overflow-hidden"
    onmousedown={(evt) => evt.preventDefault()}
  >
    <ButtonGroup>
      {#each TOOLBAR_BUTTONS as { icon: Icon, markName }}
        <Button
          variant={menuState.activeMarks.includes(markName) ? 'default' : 'secondary'}
          onclick={() => handleToggle(markName)}
          aria-label={markName}
        >
          <Icon />
        </Button>
      {/each}
    </ButtonGroup>
  </div>
{/if}

// examples/chat-reatom-react/src/components/editor/FloatingToolbar.tsx
import { BoldIcon, ItalicIcon, CodeIcon } from "lucide-react";
import { Button } from "@/components/ui/button";
import { ButtonGroup } from "@/components/ui/button-group";
import { toggleMarkCommand, isMarkActive, schema } from "./utils";
import type { EditorView } from "prosemirror-view";
import type { FloatingToolbarState } from "./floatingToolbarPlugin";

interface FloatingToolbarProps {
  state: FloatingToolbarState;
  view: EditorView;
}

export function FloatingToolbar({ state, view }: FloatingToolbarProps) {
  if (!state.visible) return null;

  const editorState = view.state;

  const runMark = (markName: "strong" | "em" | "code") => {
    const mark = schema.marks[markName];
    toggleMarkCommand(mark)(editorState, view.dispatch, view);
    view.focus();
  };

  return (
    <div className="absolute z-50 -translate-x-1/2" style={{ top: state.top, left: state.left }}>
      <ButtonGroup>
        <Button
          variant={isMarkActive(editorState, schema.marks.strong) ? "default" : "ghost"}
          size="icon-xs"
          onMouseDown={(e) => {
            e.preventDefault();
            runMark("strong");
          }}
          title="Bold (Cmd+B)"
        >
          <BoldIcon />
        </Button>
        <Button
          variant={isMarkActive(editorState, schema.marks.em) ? "default" : "ghost"}
          size="icon-xs"
          onMouseDown={(e) => {
            e.preventDefault();
            runMark("em");
          }}
          title="Italic (Cmd+I)"
        >
          <ItalicIcon />
        </Button>
        <Button
          variant={isMarkActive(editorState, schema.marks.code) ? "default" : "ghost"}
          size="icon-xs"
          onMouseDown={(e) => {
            e.preventDefault();
            runMark("code");
          }}
          title="Code (Cmd+`)"
        >
          <CodeIcon />
        </Button>
      </ButtonGroup>
    </div>
  );
}
