// homepage/homepage/content/docs/code-snippets/quickstart/NewBand.tsx
"use client";
import { useAccount } from "jazz-tools/react";
import { JazzFestAccount } from "@/app/schema";
import { useState } from "react";

export function NewBand() {
  const { me } = useAccount(JazzFestAccount, {
    resolve: { root: { myFestival: true } },
  });
  const [name, setName] = useState("");

  const handleSave = () => {
    if (!me) return; // not loaded yet
    me.root.myFestival.$jazz.push({ name });
    setName("");
  };

  return (
    <div>
      <input
        type="text"
        value={name}
        placeholder="Band name"
        onChange={(e) => setName(e.target.value)}
      />
      <button type="button" onClick={handleSave}>
        Add
      </button>
    </div>
  );
}

// homepage/homepage/content/docs/code-snippets/quickstart/NewBand.svelte
<script lang="ts">
	import { AccountCoState } from "jazz-tools/svelte";
	import { JazzFestAccount } from "$lib/schema";

  const me = new AccountCoState(JazzFestAccount, {
    resolve: { root: { myFestival: true } }
  });
  let name = $state("");

  function handleSave() {
    if (!me.current) return; // not loaded yet
    me.current.root.myFestival.$jazz.push({ name });
    name = "";
  }
</script>

<div>
  <input type="text" bind:value={name} placeholder="Band name" />
  <button type="button" onclick={handleSave}>Add</button>
</div>
