// examples/chat-svelte/src/components/chat/ChatFile.svelte
<script lang="ts">
  import type { ID } from 'jazz-tools';
  import { co } from 'jazz-tools';
  import { CoState } from 'jazz-tools/svelte';
  import { Download } from 'lucide-svelte';
  import { Button } from '@/components/ui/button';
  import { downloadBlob, formatBytes } from '@/lib/utils';
  import { toast } from 'svelte-sonner';

  interface Props {
    fileId: ID<typeof co.fileStream>;
  }

  let { fileId }: Props = $props();

  const fileStreamSchema = co.fileStream();
  const fileState = new CoState(fileStreamSchema, () => fileId);
  const file = $derived(fileState.current);

  const fileName = $derived(file.$isLoaded ? file.getMetadata()?.fileName : '');
  const fileSize = $derived(file.$isLoaded ? file.getMetadata()?.totalSizeBytes : 0);

  async function handleDownload() {
    if (!file.$isLoaded) return;
    const blob = file.toBlob();
    if (!blob) {
      toast.error('File was corrupted');
      return;
    }
    downloadBlob(blob, fileName || 'download');
  }
</script>

{#if file.$isLoaded}
  <div class="my-2 flex flex-col rounded-xl">
    <span class="mb-2 break-words">{fileName}</span>
    <Button variant="secondary" onclick={handleDownload}>
      <Download class="size-4" />
      Download
      {#if fileSize}
        <span class="text-sm">({formatBytes(fileSize)})</span>
      {/if}
    </Button>
  </div>
{:else}
  <div class="text-muted-foreground text-sm">{file.$jazz.loadingState ?? 'Loading'}...</div>
{/if}

// examples/chat-react/src/components/chat/ChatFile.tsx
import { type MouseEvent, type PointerEvent } from "react";
import { useDb } from "jazz-tools/react";
import { DownloadIcon } from "lucide-react";
import { Button } from "@/components/ui/button";
import { downloadBlob, formatBytes } from "@/lib/utils";
import { app, type Attachment } from "../../../schema/app.js";

interface ChatFileProps {
  attachment: Attachment;
}

export function ChatFile({ attachment }: ChatFileProps) {
  const db = useDb();

  const handleDownload = async () => {
    const blob = await db.loadFileAsBlob(app, attachment.fileId);
    downloadBlob(blob, attachment.name);
  };

  return (
    <div className="rounded-xl my-2 flex flex-col">
      <span className="mb-2 wrap-anywhere">{attachment.name}</span>
      <Button
        variant="secondary"
        onClick={(event) => {
          event.stopPropagation();
          void handleDownload();
        }}
        onPointerDown={(event) => {
          event.stopPropagation();
        }}
      >
        <DownloadIcon />
        Download{" "}
        {attachment.size > 0 && <span className="text-sm">({formatBytes(attachment.size)})</span>}
      </Button>
    </div>
  );
}
