// examples/chat-svelte/src/components/chat/ChatMessage.svelte
<script lang="ts">
  import type { ID } from 'jazz-tools';
  import DOMPurify from 'dompurify';
  import { AccountCoState, CoState } from 'jazz-tools/svelte';
  import { Trash2 } from 'lucide-svelte';
  import ChatFile from '@/components/chat/ChatFile.svelte';
  import ChatImage from '@/components/chat/ChatImage.svelte';
  import ChatMetadata from '@/components/chat/ChatMetadata.svelte';
  import ChatReactionPicker from '@/components/chat/ChatReactionPicker.svelte';
  import ChatReactions from '@/components/chat/ChatReactions.svelte';
  import CollaborativeCanvas from '@/components/canvas/CollaborativeCanvas.svelte';
  import * as AlertDialog from '@/components/ui/alert-dialog';
  import * as DropdownMenu from '@/components/ui/dropdown-menu';
  import { Item, ItemContent } from '@/components/ui/item';
  import { cn } from '@/lib/utils';
  import { ChatAccount, Message } from '@/lib/schema';

  interface Props {
    messageId: ID<typeof Message>;
    onDelete: (id: ID<typeof Message>) => Promise<void>;
  }

  let { messageId, onDelete }: Props = $props();

  const account = new AccountCoState(ChatAccount);
  const msg = $derived(new CoState(Message, messageId));
  const message = $derived(msg.current);
  const me = $derived(account.current);
  const currentUserId = $derived(me.$isLoaded ? me.$jazz.id : undefined);
  const isMe = $derived(
    !!currentUserId && message.$isLoaded && message.$jazz.createdBy === currentUserId
  );

  const sanitised = $derived(message.$isLoaded && DOMPurify.sanitize(message.text.toString()));

  let isMenuOpen = $state(false);
  let isDeleteDialogOpen = $state(false);

  function handleEmojiSelect(emoji: string) {
    if (!message.$isLoaded) return;
    const current = message.reactions.byMe?.value;
    message.reactions.$jazz.push(current === emoji ? '' : emoji);
    isMenuOpen = false;
  }

  async function handleDeleteConfirm() {
    await onDelete(message.$jazz.id);
    isDeleteDialogOpen = false;
  }
</script>

{#if message.$isLoaded}
  <article
    class={cn('flex max-w-[7/8] flex-col', isMe ? 'self-end items-end' : 'self-start items-start')}
  >
    <ChatMetadata date={message.$jazz.createdAt} sender={message.$jazz.createdBy} />

    <DropdownMenu.Root open={isMenuOpen} onOpenChange={(v) => (isMenuOpen = v ?? false)}>
      <DropdownMenu.Trigger>
        <Item
          variant="outline"
          class={cn(
            'max-w-full inline-flex cursor-pointer select-none px-2 py-1 shadow-xs',
            isMe ? 'border-0 bg-primary text-primary-foreground' : 'bg-background'
          )}
        >
          <ItemContent class="relative mt-0 text-base">
            {#if message.attachment}
              {#if message.attachment.type === 'image' && message.attachment.attachment.$jazz.id}
                <div class="mb-2">
                  <ChatImage imageId={message.attachment.attachment.$jazz.id} />
                </div>
              {/if}
              {#if message.attachment.type === 'file' && message.attachment.attachment.$jazz.id}
                <div class="mb-2">
                  <ChatFile fileId={message.attachment.attachment.$jazz.id} />
                </div>
              {/if}
              {#if message.attachment.type === 'canvas' && message.attachment.canvas.$jazz.id}
                <div class="mb-2">
                  <CollaborativeCanvas
                    canvasId={message.attachment.canvas.$jazz.id}
                    showControls={true}
                    class="w-full"
                  />
                </div>
              {/if}
            {/if}

            <div class="wrap-anywhere max-w-full whitespace-pre-line" aria-label="Message content">
              <!-- eslint-disable-next-line svelte/no-at-html-tags this string is sanitised -->
              {@html sanitised}
            </div>

            <ChatReactions
              {currentUserId}
              {isMe}
              reactions={message.reactions}
              onToggle={(emoji) => handleEmojiSelect(emoji)}
            />
          </ItemContent>
        </Item>
      </DropdownMenu.Trigger>
      <DropdownMenu.Content align={isMe ? 'end' : 'start'}>
        <ChatReactionPicker
          onPick={(emoji) => {
            handleEmojiSelect(emoji);
          }}
        />
        {#if isMe}
          <DropdownMenu.Item
            variant="destructive"
            onSelect={(e) => {
              e.preventDefault();
              isDeleteDialogOpen = true;
              isMenuOpen = false;
            }}
          >
            <Trash2 class="size-4" />
            Delete
          </DropdownMenu.Item>
        {/if}
      </DropdownMenu.Content>
    </DropdownMenu.Root>

    <AlertDialog.Root
      open={isDeleteDialogOpen}
      onOpenChange={(v) => (isDeleteDialogOpen = v ?? false)}
    >
      <AlertDialog.Content>
        <AlertDialog.Header>
          <AlertDialog.Title>Are you absolutely sure?</AlertDialog.Title>
          <AlertDialog.Description>
            This action cannot be undone. This will permanently delete your message from our
            servers.
          </AlertDialog.Description>
        </AlertDialog.Header>
        <AlertDialog.Footer>
          <AlertDialog.Cancel>Cancel</AlertDialog.Cancel>
          <AlertDialog.Action
            class="bg-destructive text-destructive-foreground hover:bg-destructive/90"
            onclick={handleDeleteConfirm}
          >
            Yes, delete it
          </AlertDialog.Action>
        </AlertDialog.Footer>
      </AlertDialog.Content>
    </AlertDialog.Root>
  </article>
{/if}

// examples/chat-react/src/components/chat/ChatMessage.tsx
import type { co, ID } from "jazz-tools";
import { Suspense, useState } from "react";
import DOMPurify from "dompurify";
import { useSuspenseAccount } from "jazz-tools/react";
import { TrashIcon } from "lucide-react";
import { CollaborativeCanvas } from "@/components/canvas/Canvas";
import { ChatFile } from "@/components/chat/ChatFile";
import { ChatImage } from "@/components/chat/ChatImage";
import { ChatMetadata } from "@/components/chat/ChatMetadata";
import { ReactionPicker } from "@/components/chat/ChatReactionPicker";
import { MessageReactions } from "@/components/chat/ChatReactions";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { Item, ItemContent, ItemHeader } from "@/components/ui/item";
import { ChatAccount, type Message } from "@/schema";

interface ChatMessageProps {
  message: co.loaded<
    typeof Message,
    {
      text: true;
      attachment: true;
      reactions: true;
    }
  >;
  onDelete: (id: ID<typeof Message>) => Promise<void>;
}

export const ChatMessage = ({ message, onDelete }: ChatMessageProps) => {
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  const [isDeleteDialogOpen, setIsDeleteDialogOpen] = useState(false);
  const me = useSuspenseAccount(ChatAccount);
  const isMe = message.$jazz.createdBy === me.$jazz.id;
  const sanitised = DOMPurify.sanitize(message.text.toString());

  const handleEmojiSelect = (emoji: string) => {
    // Toggle if my current reaction is being clicked on,
    // otherwise switch to the new reaction.
    const current = message.reactions.byMe?.value;
    message.reactions.$jazz.push(current === emoji ? "" : emoji);
  };

  const handleDeleteConfirm = async () => {
    await onDelete(message.$jazz.id);
    setIsDeleteDialogOpen(false);
  };

  return (
    <Suspense>
      <article
        className={`max-w-7/8 flex flex-col ${
          isMe ? "self-end items-end" : "self-start items-start"
        }`}
      >
        <ChatMetadata
          date={message.$jazz.createdAt}
          sender={message.$jazz.createdBy}
        />

        <DropdownMenu open={isMenuOpen} onOpenChange={setIsMenuOpen}>
          <DropdownMenuTrigger asChild>
            <Item
              variant="outline"
              className={`
                max-w-full inline-flex px-2 pt-0 py-1 shadow-xs cursor-pointer select-none
                ${isMe ? "border-0 bg-primary-500 text-white" : "bg-background"}
              `}
            >
              <ItemContent className="mt-0 text-base relative">
                {message.attachment?.type === "image" && (
                  <ItemHeader>
                    <Suspense>
                      <ChatImage
                        imageId={message.attachment.attachment.$jazz.id}
                      />
                    </Suspense>
                  </ItemHeader>
                )}

                {message.attachment?.type === "file" && (
                  <Suspense>
                    <ChatFile fileId={message.attachment.attachment.$jazz.id} />
                  </Suspense>
                )}

                {message.attachment?.type === "canvas" && (
                  <Suspense>
                    <CollaborativeCanvas
                      canvasId={message.attachment.canvas.$jazz.id}
                      showControls={true}
                      className="w-full"
                    />
                  </Suspense>
                )}

                <div
                  className="whitespace-pre-line max-w-full wrap-anywhere"
                  // biome-ignore lint/security/noDangerouslySetInnerHtml: This string is sanitized
                  dangerouslySetInnerHTML={{ __html: sanitised }}
                />

                <MessageReactions
                  messageId={message.$jazz.id}
                  currentUserId={me.$jazz.id}
                  isMe={isMe}
                />
              </ItemContent>
            </Item>
          </DropdownMenuTrigger>
          <DropdownMenuContent align={isMe ? "end" : "start"}>
            <ReactionPicker
              onPick={(evt) => {
                handleEmojiSelect(evt);
                setIsMenuOpen(false);
              }}
            />

            {isMe && (
              <DropdownMenuItem
                variant="destructive"
                onSelect={(evt) => {
                  evt.preventDefault();
                  setIsDeleteDialogOpen(true);
                  setIsMenuOpen(false);
                }}
              >
                <TrashIcon /> Delete
              </DropdownMenuItem>
            )}
          </DropdownMenuContent>
        </DropdownMenu>
      </article>

      <AlertDialog
        open={isDeleteDialogOpen}
        onOpenChange={setIsDeleteDialogOpen}
      >
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Are you absolutely sure?</AlertDialogTitle>
            <AlertDialogDescription>
              This action cannot be undone. This will permanently delete your
              message from our servers.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancel</AlertDialogCancel>
            <AlertDialogAction
              variant="destructive"
              onClick={handleDeleteConfirm}
            >
              Yes, delete it
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </Suspense>
  );
};
