// examples/chat-svelte/src/components/ui/label/label.svelte
<script lang="ts">
  import { Label as LabelPrimitive } from 'bits-ui';
  import { cn } from '@/lib/utils';

  let {
    ref = $bindable(null),
    class: className,
    ...restProps
  }: LabelPrimitive.RootProps = $props();
</script>

<LabelPrimitive.Root
  bind:ref
  data-slot="label"
  class={cn(
    'flex items-center gap-2 text-sm leading-none font-medium select-none group-data-[disabled=true]:pointer-events-none group-data-[disabled=true]:opacity-50 peer-disabled:cursor-not-allowed peer-disabled:opacity-50',
    className
  )}
  {...restProps}
/>

// homepage/design-system/src/components/atoms/Label.tsx
import { Label as LabelRadix } from "radix-ui";
import * as React from "react";

import { clsx } from "clsx";

export function Label({
  className,
  ...props
}: React.ComponentProps<typeof LabelRadix.Root>) {
  return (
    <LabelRadix.Root
      data-slot="label"
      className={clsx(
        "flex items-center gap-2 text-sm leading-none font-medium select-none group-data-[disabled=true]:pointer-events-none group-data-[disabled=true]:opacity-50 peer-disabled:cursor-not-allowed peer-disabled:opacity-50",
        className,
      )}
      {...props}
    />
  );
}
