// examples/chat-reatom-react/src/components/profile/Profile.tsx
import { Suspense, useState } from "react";
import { reatomComponent } from "@reatom/react";
import { wrap } from "@reatom/core";
import { LogOutIcon } from "lucide-react";
import { Avatar } from "@/components/Avatar";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Sheet,
  SheetContent,
  SheetDescription,
  SheetFooter,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from "@/components/ui/sheet";
import { jazz } from "@/jazz";
import { myProfile } from "@/model/my-profile";
import { logOut } from "@/lib/utils";
import { app } from "../../../schema.js";

interface ProfileProps {
  onClose: () => void;
  children: React.ReactNode;
}

export function Profile({ onClose, children }: ProfileProps) {
  const [open, setOpen] = useState(false);

  return (
    <Sheet
      onOpenChange={(v) => {
        setOpen(v);
        if (!v) onClose?.();
      }}
      open={open}
    >
      <SheetTrigger asChild>{children}</SheetTrigger>
      <SheetContent className="overflow-y-auto">
        <Suspense
          fallback={
            <div className="p-8 text-center text-muted-foreground italic">Loading account...</div>
          }
        >
          <ProfileContent setOpen={setOpen} />
        </Suspense>
      </SheetContent>
    </Sheet>
  );
}

const ProfileContent = reatomComponent(({ setOpen }: { setOpen: (v: boolean) => void }) => {
  const { db } = jazz();
  const profile = myProfile();

  const handleNameChange = (newName: string) => {
    if (profile) {
      db.update(app.profiles, profile.id, { name: newName });
    }
  };

  const handleAvatarChange = async (evt: React.ChangeEvent<HTMLInputElement>) => {
    if (!profile || !evt.target.files?.[0]) return;
    const file = evt.target.files[0];
    const reader = new FileReader();
    reader.onload = wrap(() => {
      const dataUrl = reader.result as string;
      db.update(app.profiles, profile.id, { avatar: dataUrl });
    });
    reader.readAsDataURL(file);
  };

  const handleAvatarRemove = () => {
    if (!profile) return;
    // TODO remove cast once https://github.com/garden-co/jazz2/pull/349 is merged
    db.update(app.profiles, profile.id, { avatar: null as unknown as string });
  };

  return (
    <>
      <SheetHeader>
        <SheetTitle>Your Account</SheetTitle>
      </SheetHeader>

      <SheetDescription className="sr-only">
        Manage your account settings and preferences.
      </SheetDescription>
      <div className="px-4 space-y-4">
        <div className="space-y-2">
          <Label htmlFor="avatar">Avatar</Label>
          <p className="text-xs text-muted-foreground">Upload a profile picture.</p>
          <div className="flex items-center gap-3">
            <label className="cursor-pointer transition-opacity hover:opacity-80">
              <Avatar
                profileId={profile?.id ?? ""}
                avatarData={profile?.avatar ?? undefined}
                size={64}
              />
              <input
                type="file"
                className="hidden"
                id="avatar"
                accept="image/*"
                ref={(el) => {
                  if (el)
                    (el as unknown as Record<string, unknown>).__handleAvatarChange =
                      handleAvatarChange;
                }}
                onChange={handleAvatarChange}
              />
            </label>
            {profile?.avatar && (
              <Button variant="outline" onClick={handleAvatarRemove}>
                Remove
              </Button>
            )}
          </div>
        </div>

        <div className="space-y-2">
          <Label htmlFor="name">Name</Label>
          <p className="text-xs text-muted-foreground">The name you would like to be known by.</p>
          <Input
            type="text"
            id="name"
            value={profile?.name ?? ""}
            onChange={(evt) => handleNameChange(evt.currentTarget.value)}
          />
        </div>
      </div>
      <SheetFooter>
        <div className="space-y-2">
          <Label htmlFor="logout">Log Out</Label>
          <p className="text-xs text-muted-foreground">
            If you log out, you will be automatically provisioned with a new local-first identity.
          </p>
          <Button
            id="logout"
            variant="destructive"
            onClick={() => {
              logOut();
              setOpen(false);
            }}
          >
            <LogOutIcon /> Log Out
          </Button>
        </div>
      </SheetFooter>
    </>
  );
}, "ProfileContent");

// examples/chat-svelte/src/components/profile/Profile.svelte
<script lang="ts">
  import { AccountCoState } from 'jazz-tools/svelte';
  import { usePasskeyAuth } from 'jazz-tools/svelte';
  import { Fingerprint, LogOut } from 'lucide-svelte';
  import * as Sheet from '@/components/ui/sheet';
  import { Button } from '@/components/ui/button';
  import { Input } from '@/components/ui/input';
  import { Label } from '@/components/ui/label';
  import Avatar from '@/components/Avatar.svelte';
  import ProfilePassphrase from '@/components/profile/ProfilePassphrase.svelte';
  import { ChatAccountWithProfile } from '@/lib/schema';

  interface Props {
    open: boolean;
    onOpenChange: (open: boolean) => void;
  }

  let { open, onOpenChange }: Props = $props();

  const account = new AccountCoState(ChatAccountWithProfile);
  const me = $derived(account.current);
  const passkeyAuth = usePasskeyAuth({ appName: 'Jazz Chat' });
</script>

<Sheet.Root {open} {onOpenChange}>
  <Sheet.Content side="right" role="dialog">
    <Sheet.Header>
      <Sheet.Title>Your Account</Sheet.Title>
      <Sheet.Description class="sr-only">
        Manage your account settings and preferences.
      </Sheet.Description>
    </Sheet.Header>
    {#if me.$isLoaded}
      <div class="grid flex-1 auto-rows-min gap-6 px-4 overflow-y-auto">
        <div>
          <Label {...{ for: 'name' }}>Name</Label>
          <p class="text-muted-foreground text-sm">The name you would like to be known by.</p>
          <Input
            id="name"
            type="text"
            class="mt-1"
            value={me.profile.name}
            oninput={(e) => me.profile.$jazz.set('name', e.currentTarget.value)}
          />
        </div>
        <Avatar editable />
        <div>
          <Label {...{ for: 'passkey-register' }}>Passkey</Label>
          <p class="text-muted-foreground text-sm">
            A passkey allows you to log back in quickly and easily.
          </p>
          <Button
            id="passkey-register"
            variant="secondary"
            class="mt-2"
            onclick={async () => {
              await passkeyAuth.current.signUp(me.profile.name);
              onOpenChange(false);
            }}
          >
            <Fingerprint class="size-4" />
            Register a passkey
          </Button>
        </div>
        <ProfilePassphrase />
      </div>
      <Sheet.Footer>
        <Label {...{ for: 'logout' }}>Log Out</Label>
        <p class="text-muted-foreground text-sm">
          If you log out, you will be automatically provisioned with a new anonymous account.
        </p>
        <Button
          id="profile-logout"
          variant="destructive"
          class="mt-2"
          onclick={() => {
            account.logOut();
            onOpenChange(false);
          }}
        >
          <LogOut />
          Log out
        </Button>
      </Sheet.Footer>
    {:else}
      <p class="text-muted-foreground p-8 text-center italic">Loading account...</p>
    {/if}
  </Sheet.Content>
</Sheet.Root>
