// examples/docs/todo-client-localfirst-vue/src/AuthAnonymousToken.vue
<script setup lang="ts">
  import { createJazzClient, JazzProvider } from "jazz-tools/vue";

  const client = createJazzClient({
    appId: "my-app",
    localAuthMode: "anonymous",
    localAuthToken: "device-token-123",
  });
</script>

<template>
  <JazzProvider :client="client">
    <slot />
  </JazzProvider>
</template>

// examples/docs/todo-client-localfirst-svelte/src/AuthAnonymousToken.svelte
<!-- #region auth-anon-token-svelte -->
<script lang="ts">
	import { createJazzClient, JazzSvelteProvider } from 'jazz-tools/svelte';

	const client = createJazzClient({
		appId: 'my-app',
		localAuthMode: 'anonymous',
		localAuthToken: 'device-token-123',
	});
</script>

<JazzSvelteProvider {client}>
	{#snippet children({ db })}
		<slot />
	{/snippet}
</JazzSvelteProvider>
<!-- #endregion auth-anon-token-svelte -->
