// examples/docs/todo-client-localfirst-vue/src/ConditionalQueryExample.vue
<!-- #region reading-conditional-query-vue -->
<script setup lang="ts">
import { ref, computed } from "vue";
import { useAll } from "jazz-tools/vue";
import { app } from "../schema/app.js";

const filter = ref<string | null>(null);
const query = computed(() =>
  filter.value ? app.todos.where({ title: { contains: filter.value } }) : undefined,
);
const filtered = useAll(query);
</script>

<template>
  <input v-model="filter" placeholder="Filter by title" />
  <ul v-if="filtered">
    <li v-for="todo in filtered" :key="todo.id">{{ todo.title }}</li>
  </ul>
</template>
<!-- #endregion reading-conditional-query-vue -->

// examples/docs/todo-client-localfirst-svelte/src/ConditionalQueryExample.svelte
<!-- #region reading-conditional-query-svelte -->
<script lang="ts">
  import { QuerySubscription } from 'jazz-tools/svelte';
  import { app } from '../schema/app.js';

  let filter = $state<string | null>(null);

  const filtered = new QuerySubscription(
    () => filter ? app.todos.where({ title: { contains: filter } }) : undefined,
  );
</script>

<input bind:value={filter} placeholder="Filter by title" />
{#if filtered.current}
  <ul>
    {#each filtered.current as todo}
      <li>{todo.title}</li>
    {/each}
  </ul>
{/if}
<!-- #endregion reading-conditional-query-svelte -->
