// examples/docs/todo-client-localfirst-vue/src/LiveQueryExample.vue
<!-- #region reading-loading-state-vue -->
<script setup lang="ts">
import { useAll } from "jazz-tools/vue";
import { app } from "../schema.js";

const todos = useAll(app.todos);
// undefined = not yet connected; [] = connected, no rows; [...] = rows present
</script>

<template>
  <p v-if="todos === undefined">Connecting…</p>
  <ul v-else>
    <li v-for="todo in todos" :key="todo.id">{{ todo.title }}</li>
  </ul>
</template>
<!-- #endregion reading-loading-state-vue -->

// examples/docs/todo-client-localfirst-svelte/src/LiveQueryExample.svelte
<!-- #region reading-loading-state-svelte -->
<script lang="ts">
  import { QuerySubscription } from 'jazz-tools/svelte';
  import { app } from '../schema.js';

  const todos = new QuerySubscription(app.todos);
  // .current: undefined = not yet connected; [] = connected, no rows; [...] = rows present
</script>

{#if todos.current === undefined}
  <p>Connecting…</p>
{:else}
  <ul>
    {#each todos.current as todo}
      <li>{todo.title}</li>
    {/each}
  </ul>
{/if}
<!-- #endregion reading-loading-state-svelte -->
