// examples/docs/todo-client-localfirst-vue/src/QuerySubscriptionExample.vue
<!-- #region query-subscription-vue -->
<script setup lang="ts">
import { useAll } from "jazz-tools/vue";
import { app } from "../schema.js";

const todos = useAll(app.todos.where({ done: false }));
</script>

<template>
  <li v-for="todo in todos ?? []" :key="todo.id">{{ todo.title }}</li>
</template>
<!-- #endregion query-subscription-vue -->

// examples/docs/todo-client-localfirst-svelte/src/QuerySubscriptionExample.svelte
<!-- #region query-subscription-svelte -->
<script lang="ts">
  import { QuerySubscription } from 'jazz-tools/svelte';
  import { app } from '../schema.js';

  const todos = new QuerySubscription(
    app.todos.where({ done: false }),
  );
</script>

{#each todos.current ?? [] as todo}
  <li>{todo.title}</li>
{/each}
<!-- #endregion query-subscription-svelte -->
