// examples/docs/todo-client-localfirst-vue/src/quickstart-list.vue
<script setup lang="ts">
import { useAll } from "jazz-tools/vue";
import { app } from "../schema/app.js";
import TodoItem from "./TodoItem.vue";
import AddTodo from "./AddTodo.vue";

const todos = useAll(app.todos);
</script>

<template>
  <ul>
    <TodoItem v-for="todo in todos ?? []" :key="todo.id" :id="todo.id" />
  </ul>
  <AddTodo />
</template>

// examples/docs/todo-client-localfirst-svelte/src/quickstart-list.svelte
<script lang="ts">
  import { QuerySubscription } from 'jazz-tools/svelte';
  import { app } from '../schema/app.js';
  import TodoItem from './TodoItem.svelte';
  import AddTodo from './AddTodo.svelte';

  const todos = new QuerySubscription(app.todos);
</script>

<ul>
  {#each todos.current ?? [] as todo (todo.id)}
    <TodoItem id={todo.id} />
  {/each}
</ul>
<AddTodo />
