// examples/docs/todo-client-localfirst-react/src/App.tsx
import * as React from "react";
import { JazzProvider } from "jazz-tools/react";
import type { DbConfig } from "jazz-tools";
import { TodoList } from "./TodoList.js";

function readEnvAppId(): string | undefined {
  return (import.meta as ImportMeta & { env?: Record<string, string | undefined> }).env
    ?.JAZZ_APP_ID;
}

function defaultConfig(overrides: Partial<DbConfig> = {}): DbConfig {
  return {
    appId: readEnvAppId() ?? "todo-react-example",
    env: "dev",
    userBranch: "main",
    ...overrides,
  };
}

type AppProps = {
  config?: Partial<DbConfig>;
  fallback?: React.ReactNode;
};

// #region context-setup-react
export function App({ config, fallback }: AppProps = {}) {
  const resolvedConfig = defaultConfig(config);
  return (
    <JazzProvider config={resolvedConfig} fallback={fallback ?? <p>Loading...</p>}>
      <h1>Todos</h1>
      <TodoList />
    </JazzProvider>
  );
}
// #endregion context-setup-react

// examples/todo-client-localfirst-svelte/src/App.svelte
<script lang="ts">
	import {
		createJazzClient,
		JazzSvelteProvider,
	} from 'jazz-tools/svelte';
	import { loadOrCreateIdentitySeed, mintSelfSignedToken, type DbConfig } from 'jazz-tools';
	import TodoList from './TodoList.svelte';

	interface Props {
		config?: Partial<DbConfig>;
	}

	let { config: configOverrides = {} }: Props = $props();

	function readEnvAppId(): string | undefined {
		return (import.meta as ImportMeta & { env?: Record<string, string | undefined> }).env
			?.JAZZ_APP_ID;
	}

	// #region context-setup-svelte
	function defaultConfig(overrides: Partial<DbConfig> = {}): DbConfig {
		const appId = overrides.appId ?? readEnvAppId() ?? '019d4349-2408-7275-9b65-ac87f62b7aa2';
		const seed = loadOrCreateIdentitySeed(appId);
		const jwtToken = mintSelfSignedToken(seed.seed, appId);

		return {
			appId,
			env: 'dev',
			userBranch: 'main',
			jwtToken,
			...overrides,
		};
	}
	// #endregion context-setup-svelte

	const config = defaultConfig(configOverrides);
	const client = createJazzClient(config);
</script>

<JazzSvelteProvider {client}>
	{#snippet children({ db })}
		<h1>Todos</h1>
		<TodoList />
	{/snippet}
	{#snippet fallback()}
		<p>Loading...</p>
	{/snippet}
</JazzSvelteProvider>
