// examples/todo-client-localfirst-vue/src/TodoList.vue
<script setup lang="ts">
import { computed, ref } from "vue";
import { useAll, useDb, useSession } from "jazz-tools/vue";
import { toast } from "vue-sonner";
import { app } from "./lib/schema.js";

const db = useDb();
// #region reading-reactive-vue
const todos = useAll(app.todos);
// #endregion reading-reactive-vue
const session = useSession();
const sessionUserId = computed(() => session?.user_id ?? null);
const title = ref("");

function handleSubmit(e: Event) {
  e.preventDefault();
  if (!title.value.trim() || !sessionUserId.value) return;
  db.insert(app.todos, {
    title: title.value.trim(),
    done: false,
    owner_id: sessionUserId.value,
  });
  title.value = "";
}

function toggleTodo(todo: { id: string; done: boolean }, event: Event) {
  const checkbox = event.currentTarget as HTMLInputElement;

  try {
    db.update(app.todos, todo.id, { done: !todo.done });
  } catch {
    checkbox.checked = todo.done;
    toast.error("You don't have permission to update this task");
  }
}

function deleteTodo(todoId: string) {
  try {
    db.delete(app.todos, todoId);
  } catch {
    toast.error("You don't have permission to delete this task");
  }
}
</script>

<template>
  <form @submit="handleSubmit">
    <input type="text" v-model="title" placeholder="What needs to be done?" required />
    <button type="submit" :disabled="!sessionUserId">Add</button>
  </form>
  <ul id="todo-list">
    <li v-for="todo in todos ?? []" :key="todo.id" :class="{ done: todo.done }">
      <input
        type="checkbox"
        :checked="todo.done"
        @change="(event) => toggleTodo(todo, event)"
        class="toggle"
      />
      <span>{{ todo.title }}</span>
      <small v-if="todo.description">{{ todo.description }}</small>
      <button class="delete-btn" @click="deleteTodo(todo.id)">&times;</button>
    </li>
  </ul>
</template>

// examples/todo-client-localfirst-svelte/src/TodoList.svelte
<script lang="ts">
	import { getDb, getSession, QuerySubscription } from 'jazz-tools/svelte';
	import { toast } from 'svelte-sonner';
	import { app } from './lib/schema.js';

	// #region reading-reactive-svelte
	const db = getDb();
	const todos = new QuerySubscription(app.todos);
	// #endregion reading-reactive-svelte
	const session = getSession();
	const sessionUserId = $derived(session.current?.user_id ?? null);
	let title = $state('');

	function handleSubmit(e: SubmitEvent) {
		e.preventDefault();
		if (!title.trim() || !sessionUserId) return;
		db.insert(app.todos, { title: title.trim(), done: false, owner_id: sessionUserId });
		title = '';
	}

	function toggleTodo(todo: { id: string; done: boolean }, event: Event) {
		const checkbox = event.currentTarget as HTMLInputElement;

		try {
			db.update(app.todos, todo.id, { done: !todo.done });
		} catch {
			checkbox.checked = todo.done;
			toast.error("You don't have permission to update this task");
		}
	}

	function deleteTodo(todoId: string) {
		try {
			db.delete(app.todos, todoId);
		} catch {
			toast.error("You don't have permission to delete this task");
		}
	}
</script>

<form onsubmit={handleSubmit}>
	<input
		type="text"
		bind:value={title}
		placeholder="What needs to be done?"
		required
	/>
	<button type="submit" disabled={!sessionUserId}>Add</button>
</form>
<ul id="todo-list">
	{#each todos.current ?? [] as todo (todo.id)}
			<li class={todo.done ? 'done' : ''}>
				<input
					type="checkbox"
					checked={todo.done}
					onchange={(event) => toggleTodo(todo, event)}
					class="toggle"
				/>
			<span>{todo.title}</span>
			{#if todo.description}
				<small>{todo.description}</small>
			{/if}
				<button class="delete-btn" onclick={() => deleteTodo(todo.id)}>
					&times;
				</button>
			</li>
	{/each}
</ul>
