// examples/betterauth/src/components/signup-form.tsx
"use client";

import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import type { SocialProviderList } from "better-auth/social-providers";
import { co } from "jazz-tools";
import { useAccount } from "jazz-tools/react-core";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { toast } from "sonner";
import { SSOButton } from "./SSOButton";
import { betterAuthClient } from "@/lib/auth-client";

interface Props {
  providers: SocialProviderList;
}

export function SignupForm({ providers }: Props) {
  const router = useRouter();
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");

  const me = useAccount(co.account(), { resolve: { profile: true } });

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();

    if (password !== confirmPassword) {
      toast.error("Error", {
        description: "Passwords do not match",
      });
      return;
    }

    await betterAuthClient.signUp.email(
      {
        email,
        password,
        name,
      },
      {
        onSuccess: async () => {
          if (me.$isLoaded) {
            me.profile.$jazz.set("name", name);
          }
          router.push("/");
        },
        onError: (error) => {
          toast.error("Sign up error", {
            description: error.error.message,
          });
        },
      },
    );
  };

  return (
    <div className="flex flex-col gap-6">
      <Card>
        <CardHeader className="text-center">
          <CardTitle className="text-xl">Welcome</CardTitle>
          <CardDescription>
            Sign up with one of the following providers
          </CardDescription>
        </CardHeader>
        <CardContent>
          <form onSubmit={handleSubmit}>
            <div className="grid gap-6">
              {providers.length > 0 && (
                <>
                  <div className="flex flex-col gap-4">
                    {providers?.map((provider) => (
                      <SSOButton key={provider} provider={provider} />
                    ))}
                  </div>
                  <div className="after:border-border relative text-center text-sm after:absolute after:inset-0 after:top-1/2 after:z-0 after:flex after:items-center after:border-t">
                    <span className="bg-card text-muted-foreground relative z-10 px-2">
                      Or continue with
                    </span>
                  </div>
                </>
              )}
              <div className="grid gap-6">
                <div className="grid gap-3">
                  <Label htmlFor="name">Name</Label>
                  <Input
                    id="name"
                    type="text"
                    placeholder="John Doe"
                    required
                    value={name}
                    onChange={(e) => setName(e.target.value)}
                  />
                </div>
                <div className="grid gap-3">
                  <Label htmlFor="email">Email</Label>
                  <Input
                    id="email"
                    type="email"
                    placeholder="you@example.com"
                    required
                    value={email}
                    onChange={(e) => setEmail(e.target.value)}
                  />
                </div>
                <div className="grid gap-3">
                  <Label htmlFor="password">Password</Label>
                  <Input
                    id="password"
                    type="password"
                    placeholder="********"
                    required
                    value={password}
                    onChange={(e) => setPassword(e.target.value)}
                  />
                </div>
                <div className="grid gap-3">
                  <Label htmlFor="confirmPassword">Confirm password</Label>
                  <Input
                    id="confirmPassword"
                    type="password"
                    required
                    value={confirmPassword}
                    onChange={(e) => setConfirmPassword(e.target.value)}
                  />
                </div>
                <Button type="submit" className="w-full">
                  Sign up
                </Button>
              </div>
              <div className="text-center text-sm">
                Already have an account?{" "}
                <Link
                  href="/auth/sign-in"
                  className="underline underline-offset-4"
                >
                  Sign in
                </Link>
              </div>
            </div>
          </form>
        </CardContent>
      </Card>
    </div>
  );
}

// examples/betterauth-svelte/src/lib/components/SignUpForm.svelte
<script lang="ts">
  import { Button } from "$lib/components/ui/button";
  import {
    Card,
    CardContent,
    CardDescription,
    CardHeader,
    CardTitle,
  } from "$lib/components/ui/card";
  import { Input } from "$lib/components/ui/input";
  import { Label } from "$lib/components/ui/label";
  import { Account } from "jazz-tools";
  import { goto } from "$app/navigation";

  import { toast } from "svelte-sonner";
  import { betterAuthClient } from "$lib/auth-client";
  import { AccountCoState } from "jazz-tools/svelte";

  const me = new AccountCoState(Account, { resolve: { profile: true } });

  const handleSubmit = async (e: Event) => {
    e.preventDefault();
    const target = e.target as HTMLFormElement;
    const formData = new FormData(target);
    const email = formData.get("email") as string;
    const password = formData.get("password") as string;
    const name = formData.get("name") as string;
    const confirmPassword = formData.get("confirmPassword") as string;

    if (password !== confirmPassword) {
      toast.error("Error", {
        description: "Passwords do not match",
      });
      return;
    }

    await betterAuthClient.signUp.email(
      {
        email,
        password,
        name,
      },
      {
        onSuccess: async () => {
          if (me.current.$isLoaded) {
            me.current.profile.$jazz.set("name", name);
          }
          goto("/");
        },
        onError: (error) => {
          toast.error("Sign up error", {
            description: error.error.message,
          });
        },
      },
    );
  };
</script>

<div class="flex flex-col gap-6">
  <Card>
    <CardHeader class="text-center">
      <CardTitle class="text-xl">Welcome</CardTitle>
      <CardDescription>
        Sign up with one of the following providers
      </CardDescription>
    </CardHeader>
    <CardContent>
      <form onsubmit={handleSubmit}>
        <div class="grid gap-6">
          <div class="grid gap-6">
            <div class="grid gap-3">
              <Label for="name">Name</Label>
              <Input
                id="name"
                name="name"
                type="text"
                placeholder="John Doe"
                required
              />
            </div>
            <div class="grid gap-3">
              <Label for="email">Email</Label>
              <Input
                id="email"
                type="email"
                name="email"
                placeholder="you@example.com"
                required
              />
            </div>
            <div class="grid gap-3">
              <Label for="password">Password</Label>
              <Input
                id="password"
                type="password"
                name="password"
                placeholder="********"
                required
              />
            </div>
            <div class="grid gap-3">
              <Label for="confirmPassword">Confirm password</Label>
              <Input
                id="confirmPassword"
                type="password"
                name="confirmPassword"
                required
              />
            </div>
            <Button type="submit" class="w-full">Sign up</Button>
          </div>
          <div class="text-center text-sm">
            Already have an account?{" "}
            <a href="/auth/sign-in" class="underline underline-offset-4">
              Sign in
            </a>
          </div>
        </div>
      </form>
    </CardContent>
  </Card>
</div>
