// packages/jazz-tools/src/solid/context/Provider.tsx
/**
 * @jsxImportSource solid-js
 */
import type { InstanceOfSchema } from "jazz-tools";
import {
  Account,
  type AccountClass,
  type AnyAccountSchema,
  type CoValueFromRaw,
} from "jazz-tools";
import {
  JazzBrowserContextManager,
  type JazzContextManagerProps,
} from "jazz-tools/browser";
import {
  type ParentProps,
  Show,
  createEffect,
  createMemo,
  createSignal,
  onCleanup,
} from "solid-js";
import {
  JazzContext,
  type JazzContextValue,
  JazzManagerContext,
} from "./jazz.js";

type JazzAccount = AccountClass<Account> & CoValueFromRaw<Account>;

export type JazzProviderProps<S extends JazzAccount | AnyAccountSchema> = {
  readonly enableSSR?: boolean;
} & JazzContextManagerProps<S>;

export const JazzProvider = <S extends JazzAccount | AnyAccountSchema>(
  props: ParentProps<JazzProviderProps<S>>,
) => {
  const jazzManager = createMemo(
    () =>
      new JazzBrowserContextManager<S>({
        useAnonymousFallback: props.enableSSR,
      }),
  );

  const [ctx, setCtx] = createSignal<JazzContextValue<InstanceOfSchema<S>>>();

  createEffect(() => {
    jazzManager()
      .createContext({
        sync: props.sync,
        storage: props.storage,
        guestMode: props.guestMode,
        AccountSchema: props.AccountSchema,
        defaultProfileName: props.defaultProfileName,
        onAnonymousAccountDiscarded: props.onAnonymousAccountDiscarded,
        onLogOut: props.onLogOut,
        logOutReplacement: props.logOutReplacement,
      })
      .catch((error) => {
        console.error("Error creating Jazz browser context:", error);
      });
  });

  const authStorage = () => jazzManager().getAuthSecretStorage();

  createEffect(() => {
    const unsubscribe = jazzManager().subscribe(() => {
      setCtx(jazzManager().getCurrentValue());
    });

    onCleanup(() => {
      unsubscribe();
    });
  });

  onCleanup(() => {
    jazzManager().done();
  });

  return (
    <Show when={ctx()}>
      {(ctxValue) => {
        return (
          <JazzContext.Provider value={ctxValue}>
            <JazzManagerContext.Provider value={jazzManager}>
              {props.children}
            </JazzManagerContext.Provider>
          </JazzContext.Provider>
        );
      }}
    </Show>
  );
};

// packages/jazz-tools/src/react/provider.tsx
import {
  Account,
  AccountClass,
  AnyAccountSchema,
  CoValueFromRaw,
} from "jazz-tools";
import {
  JazzBrowserContextManager,
  JazzContextManagerProps,
} from "jazz-tools/browser";
import { JazzContext, useJazzProviderCheck } from "jazz-tools/react-core";
import React, { useEffect, useMemo, useRef, useSyncExternalStore } from "react";

export type JazzProviderProps<
  S extends
    | (AccountClass<Account> & CoValueFromRaw<Account>)
    | AnyAccountSchema,
> = {
  children: React.ReactNode;
  enableSSR?: boolean;
  fallback?: React.ReactNode | null;
  authSecretStorageKey?: string;
} & JazzContextManagerProps<S>;

/** @category Context & Hooks */
export function JazzReactProvider<
  S extends
    | (AccountClass<Account> & CoValueFromRaw<Account>)
    | AnyAccountSchema,
>({
  children,
  guestMode,
  sync,
  storage,
  AccountSchema,
  defaultProfileName,
  onLogOut,
  logOutReplacement,
  onAnonymousAccountDiscarded,
  enableSSR,
  fallback = null,
  authSecretStorageKey,
}: JazzProviderProps<S>) {
  useJazzProviderCheck();

  const [contextManager] = React.useState(
    () =>
      new JazzBrowserContextManager<S>({
        useAnonymousFallback: enableSSR,
        authSecretStorageKey,
      }),
  );

  const onLogOutRefCallback = useRefCallback(onLogOut);
  const logOutReplacementRefCallback = useRefCallback(logOutReplacement);
  const onAnonymousAccountDiscardedRefCallback = useRefCallback(
    onAnonymousAccountDiscarded,
  );

  const props = useMemo(() => {
    return {
      AccountSchema,
      guestMode,
      sync,
      storage,
      defaultProfileName,
      onLogOut: onLogOutRefCallback,
      logOutReplacement: logOutReplacement
        ? logOutReplacementRefCallback
        : undefined,
      onAnonymousAccountDiscarded: onAnonymousAccountDiscarded
        ? onAnonymousAccountDiscardedRefCallback
        : undefined,
    } satisfies JazzContextManagerProps<S>;
  }, [guestMode, sync.peer, sync.when, storage]);

  if (contextManager.propsChanged(props)) {
    contextManager.createContext(props).catch((error) => {
      console.log(error.stack);
      console.error("Error creating Jazz browser context:", error);
    });
  }

  const isReady = useSyncExternalStore(
    useCallback(
      (callback) => {
        return contextManager.subscribe(callback);
      },
      [contextManager],
    ),
    () => Boolean(contextManager.getCurrentValue()),
    () => Boolean(contextManager.getCurrentValue()),
  );

  useEffect(() => {
    // In development mode we don't return a cleanup function because otherwise
    // the double effect execution would mark the context as done immediately.
    if (process.env.NODE_ENV === "development") return;

    return () => {
      contextManager.done();
    };
  }, []);

  return (
    <JazzContext.Provider value={contextManager}>
      {isReady ? children : fallback}
    </JazzContext.Provider>
  );
}

function useRefCallback<T extends (...args: any[]) => any>(callback?: T) {
  const callbackRef = React.useRef(callback);
  callbackRef.current = callback;
  return useRef(
    (...args: Parameters<T>): ReturnType<T> => callbackRef.current?.(...args),
  ).current;
}
