// packages/jazz-tools/src/svelte/SyntheticUserSwitcher.svelte
<script lang="ts">
	import type { LocalAuthMode } from '../runtime/context.js';
	import {
		createSyntheticUserProfile,
		loadSyntheticUserStore,
		saveSyntheticUserStore,
		setActiveSyntheticProfile,
		type SyntheticUserProfile,
		type SyntheticUserStorageOptions,
		type SyntheticUserStore
	} from '../synthetic-users.js';

	interface Props extends SyntheticUserStorageOptions {
		appId: string;
		class?: string;
		reloadOnSwitch?: boolean;
		onProfileChange?: (profile: SyntheticUserProfile) => void;
	}

	let {
		appId,
		class: className,
		reloadOnSwitch = true,
		onProfileChange,
		storage,
		storageKey,
		defaultMode
	}: Props = $props();

	const storageOptions: SyntheticUserStorageOptions = { storage, storageKey, defaultMode };

	let store = $state<SyntheticUserStore>(loadSyntheticUserStore(appId, storageOptions));

	function getActiveProfile(s: SyntheticUserStore): SyntheticUserProfile {
		return s.profiles.find((p) => p.id === s.activeProfileId) ?? s.profiles[0];
	}

	let activeProfile = $derived(getActiveProfile(store));

	function applyStore(nextStore: SyntheticUserStore, triggerReload: boolean) {
		saveSyntheticUserStore(appId, nextStore, storageOptions);
		store = nextStore;
		onProfileChange?.(getActiveProfile(nextStore));
		if (triggerReload && reloadOnSwitch && typeof window !== 'undefined') {
			window.location.reload();
		}
	}

	function handleSwitch(event: Event) {
		const target = event.target as HTMLSelectElement;
		const nextStore = setActiveSyntheticProfile(appId, target.value, storageOptions);
		store = nextStore;
		onProfileChange?.(getActiveProfile(nextStore));
		if (reloadOnSwitch && typeof window !== 'undefined') {
			window.location.reload();
		}
	}

	function handleModeChange(event: Event) {
		const target = event.target as HTMLSelectElement;
		const mode = target.value as LocalAuthMode;
		const nextStore: SyntheticUserStore = {
			...store,
			profiles: store.profiles.map((profile) =>
				profile.id === store.activeProfileId ? { ...profile, mode } : profile
			)
		};
		applyStore(nextStore, false);
	}

	function handleAddProfile() {
		const suggestedName = `User ${store.profiles.length + 1}`;
		const rawName =
			typeof window !== 'undefined'
				? window.prompt('New synthetic user name', suggestedName)
				: suggestedName;
		if (rawName === null) return;
		const name = rawName.trim() || suggestedName;
		const profile = createSyntheticUserProfile(name, 'demo');
		const nextStore: SyntheticUserStore = {
			activeProfileId: profile.id,
			profiles: [...store.profiles, profile]
		};
		applyStore(nextStore, true);
	}

	function handleRemoveProfile() {
		if (store.profiles.length <= 1) return;
		const nextProfiles = store.profiles.filter((p) => p.id !== store.activeProfileId);
		const nextStore: SyntheticUserStore = {
			activeProfileId: nextProfiles[0].id,
			profiles: nextProfiles
		};
		applyStore(nextStore, true);
	}
</script>

<div class={className}>
	<label>
		Synthetic User
		<select value={store.activeProfileId} onchange={handleSwitch}>
			{#each store.profiles as profile (profile.id)}
				<option value={profile.id}>{profile.name} ({profile.mode})</option>
			{/each}
		</select>
	</label>
	{' '}
	<label>
		Mode
		<select value={activeProfile.mode} onchange={handleModeChange}>
			<option value="anonymous">anonymous</option>
			<option value="demo">demo</option>
		</select>
	</label>
	{' '}
	<button type="button" onclick={handleAddProfile}>Add</button>
	{' '}
	<button type="button" disabled={store.profiles.length <= 1} onclick={handleRemoveProfile}>
		Remove
	</button>
</div>

// packages/jazz-tools/src/react/synthetic-user-switcher.tsx
import { useMemo, useState } from "react";
import type { LocalAuthMode } from "../runtime/context.js";
import {
  createSyntheticUserProfile,
  loadSyntheticUserStore,
  saveSyntheticUserStore,
  setActiveSyntheticProfile,
  type SyntheticUserProfile,
  type SyntheticUserStorageOptions,
  type SyntheticUserStore,
} from "./synthetic-users.js";

export interface SyntheticUserSwitcherProps extends SyntheticUserStorageOptions {
  appId: string;
  className?: string;
  reloadOnSwitch?: boolean;
  onProfileChange?: (profile: SyntheticUserProfile) => void;
}

function getActiveProfile(store: SyntheticUserStore): SyntheticUserProfile {
  return store.profiles.find((profile) => profile.id === store.activeProfileId) ?? store.profiles[0];
}

export function SyntheticUserSwitcher({
  appId,
  className,
  reloadOnSwitch = true,
  onProfileChange,
  ...storageOptions
}: SyntheticUserSwitcherProps) {
  const stableStorageOptions = useMemo(
    () => ({
      storage: storageOptions.storage,
      storageKey: storageOptions.storageKey,
      defaultMode: storageOptions.defaultMode,
    }),
    [storageOptions.defaultMode, storageOptions.storage, storageOptions.storageKey],
  );

  const [store, setStore] = useState<SyntheticUserStore>(() =>
    loadSyntheticUserStore(appId, stableStorageOptions),
  );
  const activeProfile = getActiveProfile(store);

  const applyStore = (nextStore: SyntheticUserStore, triggerReload: boolean) => {
    saveSyntheticUserStore(appId, nextStore, stableStorageOptions);
    setStore(nextStore);
    onProfileChange?.(getActiveProfile(nextStore));
    if (triggerReload && reloadOnSwitch && typeof window !== "undefined") {
      window.location.reload();
    }
  };

  const handleSwitch = (profileId: string) => {
    const nextStore = setActiveSyntheticProfile(appId, profileId, stableStorageOptions);
    setStore(nextStore);
    onProfileChange?.(getActiveProfile(nextStore));
    if (reloadOnSwitch && typeof window !== "undefined") {
      window.location.reload();
    }
  };

  const handleModeChange = (mode: LocalAuthMode) => {
    const nextStore: SyntheticUserStore = {
      ...store,
      profiles: store.profiles.map((profile) =>
        profile.id === store.activeProfileId ? { ...profile, mode } : profile,
      ),
    };
    applyStore(nextStore, false);
  };

  const handleAddProfile = () => {
    const suggestedName = `User ${store.profiles.length + 1}`;
    const rawName =
      typeof window !== "undefined" ? window.prompt("New synthetic user name", suggestedName) : suggestedName;
    if (rawName === null) return;
    const name = rawName.trim() || suggestedName;
    const profile = createSyntheticUserProfile(name, "demo");
    const nextStore: SyntheticUserStore = {
      activeProfileId: profile.id,
      profiles: [...store.profiles, profile],
    };
    applyStore(nextStore, true);
  };

  const handleRemoveProfile = () => {
    if (store.profiles.length <= 1) return;
    const nextProfiles = store.profiles.filter((profile) => profile.id !== store.activeProfileId);
    const nextStore: SyntheticUserStore = {
      activeProfileId: nextProfiles[0].id,
      profiles: nextProfiles,
    };
    applyStore(nextStore, true);
  };

  return (
    <div className={className}>
      <label>
        Synthetic User{" "}
        <select value={store.activeProfileId} onChange={(event) => handleSwitch(event.target.value)}>
          {store.profiles.map((profile) => (
            <option key={profile.id} value={profile.id}>
              {profile.name} ({profile.mode})
            </option>
          ))}
        </select>
      </label>
      {" "}
      <label>
        Mode{" "}
        <select
          value={activeProfile.mode}
          onChange={(event) => handleModeChange(event.target.value as LocalAuthMode)}
        >
          <option value="anonymous">anonymous</option>
          <option value="demo">demo</option>
        </select>
      </label>
      {" "}
      <button type="button" onClick={handleAddProfile}>
        Add
      </button>
      {" "}
      <button type="button" disabled={store.profiles.length <= 1} onClick={handleRemoveProfile}>
        Remove
      </button>
    </div>
  );
}
