// examples/form-svelte/src/lib/components/Orders.svelte
<script lang="ts">
  import { AccountCoState } from 'jazz-tools/svelte';
  import { JazzAccount, type BubbleTeaOrder } from '$lib/schema';
  import { type Loaded } from 'jazz-tools';
  import OrderThumbnail from './OrderThumbnail.svelte';
  import { goto } from '$app/navigation';

  const me = new AccountCoState(JazzAccount, {
    resolve: {
      profile: true,
      root: {
        orders: {
          $each: true
        }
      }
    }
  });

  const orders = $derived(me.current?.root.orders);

  function navigateToCreateOrder() {
    goto('#/order');
  }

  function navigateToEditOrder(id: string) {
    goto(`#/order/${id}`);
  }
</script>

<div>
  <h1 class="text-lg mb-4">
    <strong>Your bubble tea orders 🧋</strong>
  </h1>

  {#if orders && orders.length > 0}
    <div class="space-y-4">
      {#each orders as order}
        {#if order}
          <button 
            type="button"
            class="border rounded-lg p-4 cursor-pointer hover:bg-gray-50 text-left w-full" 
            onclick={() => navigateToEditOrder(order.id)}
          >
            <OrderThumbnail {order} />
          </button>
        {/if}
      {/each}
    </div>
  {:else}
    <p class="text-gray-500">No orders yet. Create your first order!</p>
  {/if}

  <button
    onclick={navigateToCreateOrder}
    class="mt-6 bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"
  >
    Create New Order
  </button>
</div>

// examples/tanstack-form/src/Orders.tsx
import { useAccount } from "jazz-tools/react";
import { OrderThumbnail } from "./OrderThumbnail.tsx";
import { JazzAccount } from "./schema.ts";

export function Orders() {
  const { me } = useAccount(JazzAccount, {
    resolve: { root: { orders: true } },
  });

  return (
    <>
      <section className="space-y-5">
        <a
          href={`/#/order`}
          className="block relative p-3 bg-white border border-stone-200 text-center rounded-md dark:bg-stone-900 dark:border-stone-900"
        >
          <strong>Add new order</strong>
        </a>

        <div className="space-y-3">
          <h1 className="text-lg pb-2 border-b mb-3 border-stone-200 dark:border-stone-700">
            <strong>Your orders 🧋</strong>
          </h1>

          {me?.root?.orders?.length ? (
            me?.root?.orders.map((order) =>
              order ? <OrderThumbnail key={order.id} order={order} /> : null,
            )
          ) : (
            <p>You have no orders yet.</p>
          )}
        </div>
      </section>
    </>
  );
}
