// starters/next-hybrid/components/auth-backup.tsx
"use client";

import { useState } from "react";
import { useLocalFirstAuth } from "jazz-tools/react";

type Status =
  | { kind: "idle" }
  | { kind: "error"; message: string }
  | { kind: "success"; message: string };

// In production, pin this to your deployed hostname so passkeys remain usable
// across preview deployments. Leaving it undefined falls back to location.hostname.
const PASSKEY_APP_HOSTNAME: string | undefined = undefined;
const PASSKEY_APP_NAME = "Jazz Starter";

export function AuthBackup({
  redirectAfterRestore,
  mode = "full",
}: {
  redirectAfterRestore?: string;
  mode?: "full" | "restore-only";
} = {}) {
  const auth = useLocalFirstAuth();

  function navigate() {
    if (redirectAfterRestore) location.assign(redirectAfterRestore);
  }
  const [phrase, setPhrase] = useState<string | null>(null);
  const [restoreInput, setRestoreInput] = useState("");
  const [status, setStatus] = useState<Status>({ kind: "idle" });
  const [busy, setBusy] = useState(false);

  async function handleReveal() {
    setStatus({ kind: "idle" });
    setBusy(true);
    try {
      if (!auth.secret) {
        setStatus({ kind: "error", message: "No local secret to reveal yet." });
        return;
      }
      const { RecoveryPhrase } = await import("jazz-tools/passphrase");
      setPhrase(RecoveryPhrase.fromSecret(auth.secret));
    } catch (err) {
      setStatus({ kind: "error", message: describeError(err) });
    } finally {
      setBusy(false);
    }
  }

  async function handleCopy() {
    if (!phrase) return;
    try {
      await navigator.clipboard.writeText(phrase);
      setStatus({ kind: "success", message: "Phrase copied." });
    } catch {
      setStatus({
        kind: "error",
        message: "Copy failed — select the text and copy manually.",
      });
    }
  }

  async function handleRestorePhrase(e: React.FormEvent) {
    e.preventDefault();
    setStatus({ kind: "idle" });
    setBusy(true);
    try {
      const { RecoveryPhrase } = await import("jazz-tools/passphrase");
      const secret = RecoveryPhrase.toSecret(restoreInput.trim());
      await auth.login(secret);
      navigate();
    } catch (err) {
      setStatus({ kind: "error", message: describeError(err) });
    } finally {
      setBusy(false);
    }
  }

  async function handlePasskeyBackup() {
    setStatus({ kind: "idle" });
    setBusy(true);
    try {
      if (!auth.secret) {
        setStatus({ kind: "error", message: "No local secret to back up yet." });
        return;
      }
      const { BrowserPasskeyBackup } = await import("jazz-tools/passkey-backup");
      const pb = new BrowserPasskeyBackup({
        appName: PASSKEY_APP_NAME,
        appHostname: PASSKEY_APP_HOSTNAME,
      });
      await pb.backup(auth.secret, "My account");
      setStatus({ kind: "success", message: "Passkey backup created." });
    } catch (err) {
      setStatus({ kind: "error", message: describeError(err) });
    } finally {
      setBusy(false);
    }
  }

  async function handlePasskeyRestore() {
    setStatus({ kind: "idle" });
    setBusy(true);
    try {
      const { BrowserPasskeyBackup } = await import("jazz-tools/passkey-backup");
      const pb = new BrowserPasskeyBackup({
        appName: PASSKEY_APP_NAME,
        appHostname: PASSKEY_APP_HOSTNAME,
      });
      const secret = await pb.restore();
      await auth.login(secret);
      navigate();
    } catch (err) {
      setStatus({ kind: "error", message: describeError(err) });
    } finally {
      setBusy(false);
    }
  }

  return (
    <details className="auth-backup">
      <summary>Back up or restore your local-only account</summary>
      <p className="auth-backup-hint">
        Save your account's recovery phrase or a passkey so you can get back in on another device or
        after clearing storage.
      </p>

      <div className="auth-backup-section">
        <h3>Recovery phrase</h3>
        {mode === "full" && (
          <>
            <button type="button" onClick={handleReveal} disabled={busy}>
              Show recovery phrase
            </button>
            {phrase && (
              <>
                <textarea
                  className="auth-backup-phrase"
                  readOnly
                  rows={3}
                  value={phrase}
                  aria-label="Recovery phrase"
                />
                <button type="button" onClick={handleCopy} disabled={busy}>
                  Copy
                </button>
              </>
            )}
          </>
        )}

        <form onSubmit={handleRestorePhrase} className="auth-backup-restore">
          <label htmlFor="auth-backup-restore-input">Restore from recovery phrase</label>
          <textarea
            id="auth-backup-restore-input"
            rows={3}
            value={restoreInput}
            onChange={(e) => setRestoreInput(e.target.value)}
            placeholder="Paste your 24-word phrase"
            required
          />
          <button type="submit" disabled={busy || !restoreInput.trim()}>
            Restore
          </button>
        </form>
      </div>

      <div className="auth-backup-section">
        <h3>Passkey</h3>
        <div className="auth-backup-row">
          {mode === "full" && (
            <button type="button" onClick={handlePasskeyBackup} disabled={busy}>
              Back up with passkey
            </button>
          )}
          <button type="button" onClick={handlePasskeyRestore} disabled={busy}>
            Restore with passkey
          </button>
        </div>
      </div>

      {status.kind === "error" && (
        <p className="alert-error" role="alert">
          {status.message}
        </p>
      )}
      {status.kind === "success" && (
        <p className="auth-backup-success" role="status">
          {status.message}
        </p>
      )}
    </details>
  );
}

function describeError(err: unknown): string {
  if (err && typeof err === "object" && "code" in err && "message" in err) {
    const code = String((err as { code: unknown }).code);
    const message = String((err as { message: unknown }).message);
    return `${code}: ${message}`;
  }
  if (err instanceof Error) return err.message;
  return "Unknown error";
}

// starters/sveltekit-localfirst/src/lib/AuthBackup.svelte
<script lang="ts">
  import { LocalFirstAuth } from "jazz-tools/svelte";
  import { goto } from "$app/navigation";

  // In production, pin this to your deployed hostname so passkeys remain
  // usable across preview deployments. Leaving it undefined falls back to
  // location.hostname.
  const PASSKEY_APP_HOSTNAME: string | undefined = undefined;
  const PASSKEY_APP_NAME = "Jazz Starter";

  type Status =
    | { kind: "idle" }
    | { kind: "error"; message: string }
    | { kind: "success"; message: string };

  let {
    redirectAfterRestore,
    mode = "full",
  }: {
    redirectAfterRestore?: string;
    mode?: "full" | "restore-only";
  } = $props();

  const auth = new LocalFirstAuth();

  let phrase = $state<string | null>(null);
  let restoreInput = $state("");
  let status = $state<Status>({ kind: "idle" });
  let busy = $state(false);

  async function navigate() {
    if (redirectAfterRestore) await goto(redirectAfterRestore);
  }

  function describeError(err: unknown): string {
    if (err && typeof err === "object" && "code" in err && "message" in err) {
      return `${String((err as { code: unknown }).code)}: ${String((err as { message: unknown }).message)}`;
    }
    if (err instanceof Error) return err.message;
    return "Unknown error";
  }

  async function handleReveal() {
    status = { kind: "idle" };
    busy = true;
    try {
      if (!auth.secret) {
        status = { kind: "error", message: "No local secret to reveal yet." };
        return;
      }
      const { RecoveryPhrase } = await import("jazz-tools/passphrase");
      phrase = RecoveryPhrase.fromSecret(auth.secret);
    } catch (err) {
      status = { kind: "error", message: describeError(err) };
    } finally {
      busy = false;
    }
  }

  async function handleCopy() {
    if (!phrase) return;
    try {
      await navigator.clipboard.writeText(phrase);
      status = { kind: "success", message: "Phrase copied." };
    } catch {
      status = {
        kind: "error",
        message: "Copy failed — select the text and copy manually.",
      };
    }
  }

  async function handleRestorePhrase(e: SubmitEvent) {
    e.preventDefault();
    status = { kind: "idle" };
    busy = true;
    try {
      const { RecoveryPhrase } = await import("jazz-tools/passphrase");
      const secret = RecoveryPhrase.toSecret(restoreInput.trim());
      await auth.login(secret);
      await navigate();
    } catch (err) {
      status = { kind: "error", message: describeError(err) };
    } finally {
      busy = false;
    }
  }

  async function handlePasskeyBackup() {
    status = { kind: "idle" };
    busy = true;
    try {
      if (!auth.secret) {
        status = { kind: "error", message: "No local secret to back up yet." };
        return;
      }
      const { BrowserPasskeyBackup } = await import("jazz-tools/passkey-backup");
      const pb = new BrowserPasskeyBackup({
        appName: PASSKEY_APP_NAME,
        appHostname: PASSKEY_APP_HOSTNAME,
      });
      await pb.backup(auth.secret, "My account");
      status = { kind: "success", message: "Passkey backup created." };
    } catch (err) {
      status = { kind: "error", message: describeError(err) };
    } finally {
      busy = false;
    }
  }

  async function handlePasskeyRestore() {
    status = { kind: "idle" };
    busy = true;
    try {
      const { BrowserPasskeyBackup } = await import("jazz-tools/passkey-backup");
      const pb = new BrowserPasskeyBackup({
        appName: PASSKEY_APP_NAME,
        appHostname: PASSKEY_APP_HOSTNAME,
      });
      const secret = await pb.restore();
      await auth.login(secret);
      await navigate();
    } catch (err) {
      status = { kind: "error", message: describeError(err) };
    } finally {
      busy = false;
    }
  }
</script>

<details class="auth-backup">
  <summary>Back up or restore your local-only account</summary>
  <p class="auth-backup-hint">
    Save your account's recovery phrase or a passkey so you can get back in
    on another device or after clearing storage.
  </p>

  <div class="auth-backup-section">
    <h3>Recovery phrase</h3>
    {#if mode === "full"}
      <button type="button" onclick={handleReveal} disabled={busy}>
        Show recovery phrase
      </button>
      {#if phrase}
        <textarea
          class="auth-backup-phrase"
          readonly
          rows={3}
          value={phrase}
          aria-label="Recovery phrase"
        ></textarea>
        <button type="button" onclick={handleCopy} disabled={busy}>
          Copy
        </button>
      {/if}
    {/if}

    <form onsubmit={handleRestorePhrase} class="auth-backup-restore">
      <label for="auth-backup-restore-input">
        Restore from recovery phrase
      </label>
      <textarea
        id="auth-backup-restore-input"
        rows={3}
        bind:value={restoreInput}
        placeholder="Paste your 24-word phrase"
        required
      ></textarea>
      <button type="submit" disabled={busy || !restoreInput.trim()}>
        Restore
      </button>
    </form>
  </div>

  <div class="auth-backup-section">
    <h3>Passkey</h3>
    <div class="auth-backup-row">
      {#if mode === "full"}
        <button type="button" onclick={handlePasskeyBackup} disabled={busy}>
          Back up with passkey
        </button>
      {/if}
      <button type="button" onclick={handlePasskeyRestore} disabled={busy}>
        Restore with passkey
      </button>
    </div>
  </div>

  {#if status.kind === "error"}
    <p class="alert-error" role="alert">{status.message}</p>
  {:else if status.kind === "success"}
    <p class="auth-backup-success" role="status">{status.message}</p>
  {/if}
</details>
