// packages/jazz-react/src/auth/PasskeyAuth.tsx
"use client";

import { BrowserPasskeyAuth } from "jazz-browser";
import {
  useAuthSecretStorage,
  useIsAuthenticated,
  useJazzContext,
} from "jazz-react-core";
import { useMemo, useState } from "react";

/**
 * `usePasskeyAuth` hook provides a `JazzAuth` object for passkey authentication.
 *
 * @example
 * ```ts
 * const auth = usePasskeyAuth({ appName, appHostname });
 * ```
 *
 * @category Auth Providers
 */
export function usePasskeyAuth({
  appName,
  appHostname,
}: {
  appName: string;
  appHostname?: string;
}) {
  const context = useJazzContext();
  const authSecretStorage = useAuthSecretStorage();

  if ("guest" in context) {
    throw new Error("Passkey auth is not supported in guest mode");
  }

  const authMethod = useMemo(() => {
    return new BrowserPasskeyAuth(
      context.node.crypto,
      context.authenticate,
      authSecretStorage,
      appName,
      appHostname,
    );
  }, [appName, appHostname, authSecretStorage]);

  const isAuthenticated = useIsAuthenticated();

  return {
    state: isAuthenticated ? "signedIn" : "anonymous",
    logIn: authMethod.logIn,
    signUp: authMethod.signUp,
  } as const;
}

export const PasskeyAuthBasicUI = (props: {
  appName: string;
  appHostname?: string;
  children?: React.ReactNode;
}) => {
  const [username, setUsername] = useState<string>("");
  const [error, setError] = useState<string | null>(null);

  const auth = usePasskeyAuth({
    appName: props.appName,
    appHostname: props.appHostname,
  });

  if (auth.state === "signedIn") {
    return props.children ?? null;
  }

  const { logIn, signUp } = auth;

  return (
    <div
      style={{
        width: "100vw",
        height: "100vh",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
      }}
    >
      {error && <div style={{ color: "red" }}>{error}</div>}
      <div
        style={{
          width: "18rem",
          display: "flex",
          flexDirection: "column",
          gap: "2rem",
        }}
      >
        <form
          style={{
            width: "18rem",
            display: "flex",
            flexDirection: "column",
            gap: "0.5rem",
          }}
          onSubmit={(e) => {
            e.preventDefault();
            setError(null);
            signUp(username).catch((error) => setError(error.message));
          }}
        >
          <input
            placeholder="Display name"
            value={username}
            onChange={(e) => setUsername(e.target.value)}
            autoComplete="webauthn"
            style={{
              border: "2px solid #000",
              padding: "11px 8px",
              borderRadius: "6px",
            }}
          />
          <input
            type="submit"
            value="Sign up"
            style={{
              background: "#000",
              color: "#fff",
              padding: "13px 5px",
              border: "none",
              borderRadius: "6px",
              cursor: "pointer",
            }}
          />
        </form>
        <button
          onClick={() => {
            setError(null);
            logIn().catch((error) => setError(error.message));
          }}
          style={{
            background: "#000",
            color: "#fff",
            padding: "13px 5px",
            border: "none",
            borderRadius: "6px",
            cursor: "pointer",
          }}
        >
          Log in with existing account
        </button>
      </div>
    </div>
  );
};

// packages/jazz-tools/src/solid/auth/PasskeyAuth.tsx
import { BrowserPasskeyAuth } from "jazz-tools/browser";
import { Accessor, createMemo } from "solid-js";
import { useAuthSecretStorage, useJazzContext } from "../jazz.js";
import { useIsAuthenticated } from "./useIsAuthenticated.js";

export type PasskeyAuth = {
  readonly auth: Accessor<BrowserPasskeyAuth>;
  readonly state: Accessor<"anonymous" | "signedIn">;
};

/** @category Auth Providers */
export function usePasskeyAuth({
  appName,
  appHostname,
}: {
  appName: string;
  appHostname?: string;
}): PasskeyAuth {
  const jazz = useJazzContext();
  const authSecretStorage = useAuthSecretStorage();
  const isAuthenticated = useIsAuthenticated();

  const auth = createMemo(
    () =>
      new BrowserPasskeyAuth(
        jazz().node.crypto,
        jazz().authenticate,
        authSecretStorage(),
        appName,
        appHostname,
      ),
  );

  if ("guest" in jazz()) {
    throw new Error("Passkey auth is not supported in guest mode");
  }

  const state = () => (isAuthenticated() ? "signedIn" : "anonymous");

  return { auth, state };
}
