// examples/docs/todo-client-localfirst-vue/src/App.vue
<script setup lang="ts">
import { createJazzClient, JazzProvider } from "jazz-tools/vue";
import TodoList from "./TodoList.vue";

const client = createJazzClient({
  appId: "<your-app-id>",
});
</script>

<template>
  <JazzProvider :client="client">
    <h1>Todos</h1>
    <TodoList />

    <template #fallback>
      <p>Loading...</p>
    </template>
  </JazzProvider>
</template>

// examples/docs/todo-client-localfirst-solid/src/App.tsx
import { JazzProvider, createSolidJazzClient } from "jazz-tools/solid";
import { TodoList } from "./TodoList.js";

export function App() {
  const client = createSolidJazzClient(() => ({ appId: "<your-app-id>" }));

  return (
    <JazzProvider client={client} fallback={<p>Loading...</p>}>
      <h1>Todos</h1>
      <TodoList />
    </JazzProvider>
  );
}
