// examples/docs/todo-client-localfirst-vue/src/AuthLocalfirst.vue
<script setup lang="ts">
import type { JazzSession, JazzClient } from "jazz-tools/vue";
import { JazzSessionProvider } from "jazz-tools/vue";
// Configure once with await createJazzSession({ appId, serverUrl, initial: "local-first" }).
defineProps<{ session: JazzSession<JazzClient> }>();
</script>
<template>
  <JazzSessionProvider :session="session"><slot /></JazzSessionProvider>
</template>

// examples/docs/todo-client-localfirst-solid/src/AuthLocalfirst.tsx
import { type ParentProps } from "solid-js";
import type { JazzSession } from "jazz-tools/solid";
import type { JazzClient } from "jazz-tools/client";
import { JazzSessionProvider } from "jazz-tools/solid";

// Configure once with await createJazzSession({ appId, serverUrl, initial: "local-first" }).
export function AuthLocalfirst(props: ParentProps<{ session: JazzSession<JazzClient> }>) {
  return (
    <JazzSessionProvider session={props.session} fallback={<p>Loading...</p>}>
      {props.children}
    </JazzSessionProvider>
  );
}
