// examples/docs/todo-client-localfirst-vue/src/ProviderExample.vue
<script setup lang="ts">
import type { DbConfig } from "jazz-tools";
import { JazzProvider } from "jazz-tools/vue";
// Prepare a handle outside this context with createAccountManager.
defineProps<{ config: DbConfig }>();
</script>
<template>
  <JazzProvider :config="config"><slot /></JazzProvider>
</template>

// examples/docs/todo-client-localfirst-solid/src/ProviderExample.tsx
import { type ParentProps } from "solid-js";
import type { DbConfig } from "jazz-tools";
import { JazzProvider } from "jazz-tools/solid";

// Prepare a handle outside this context with createAccountManager.
export function ProviderExample(props: ParentProps<{ config: DbConfig }>) {
  return (
    <JazzProvider config={props.config} fallback={<p>Loading...</p>}>
      {props.children}
    </JazzProvider>
  );
}
