// examples/docs/todo-client-localfirst-react/src/quickstart-add.tsx
import { useState } from "react";
import { useDb } from "jazz-tools/react";
import { app } from "../schema/app.js";

export function AddTodo() {
  const db = useDb();
  const [title, setTitle] = useState("");

  return (
    <form
      onSubmit={(e) => {
        e.preventDefault();
        db.insert(app.todos, { title, done: false });
        setTitle("");
      }}
    >
      <input
        type="text"
        value={title}
        onChange={(e) => setTitle(e.target.value)}
        placeholder="What needs to be done?"
      />
      <button type="submit">Add</button>
    </form>
  );
}

// examples/docs/todo-client-localfirst-solid/src/quickstart-add.tsx
import { createSignal } from "solid-js";
import { useDb } from "jazz-tools/solid";
import { app } from "../schema.js";

export function QuickstartAdd() {
  const db = useDb();
  const [title, setTitle] = createSignal("");

  function addTodo() {
    db().insert(app.todos, { title: title(), done: false });
    setTitle("");
  }

  return (
    <form
      onSubmit={(e) => {
        e.preventDefault();
        addTodo();
      }}
    >
      <input
        value={title()}
        onInput={(e) => setTitle(e.currentTarget.value)}
        type="text"
        placeholder="What needs to be done?"
      />
      <button type="submit">Add</button>
    </form>
  );
}
