// examples/nextjs-csr-ssr/app/TodoPanel.tsx
"use client";

import { useState, useEffect } from "react";
import { BrowserAuthSecretStore } from "jazz-tools";
import { JazzProvider } from "jazz-tools/react";
import type { DehydratedSnapshot } from "jazz-tools/backend";
import TodoForm from "./TodoForm";
import TodoList from "./TodoList";

// Pass a snapshot to seed the first render (the prefetch column does); leave it
// off and the panel just waits for the live client (the client-only column). The
// panel cares about nothing else.
export default function TodoPanel({ snapshot }: { snapshot?: DehydratedSnapshot }) {
  const [secret, setSecret] = useState("");
  const appId = process.env.NEXT_PUBLIC_JAZZ_APP_ID!;

  useEffect(() => {
    BrowserAuthSecretStore.getOrCreateSecret({ appId }).then(setSecret);
  }, [appId]);

  // No snapshot: wait for the persisted secret before connecting. With one: seed
  // the rows right away (ssr) and let the client connect on its own once it lands.
  if (!snapshot && !secret) return null;

  return (
    <JazzProvider
      config={{
        appId,
        serverUrl: process.env.NEXT_PUBLIC_JAZZ_SERVER_URL!,
        // The client-only column reuses its persisted secret; the seeded column
        // lets the client connect on its own — its rows are already on screen.
        ...(!snapshot && secret ? { secret } : {}),
      }}
      ssr={!!snapshot}
    >
      <TodoForm />
      <TodoList snapshot={snapshot} />
    </JazzProvider>
  );
}

// examples/sveltekit-csr-ssr/src/lib/TodoPanel.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { env } from "$env/dynamic/public";
  import {
    BrowserAuthSecretStore,
    createJazzClient,
    JazzSvelteProvider,
    type DehydratedSnapshot,
    type JazzClient,
  } from "jazz-tools/svelte";
  import TodoForm from "./TodoForm.svelte";
  import TodoList from "./TodoList.svelte";

  // Pass a snapshot to seed the first render (the prefetch column does); leave it
  // off and the panel just waits for the live client (the client-only column).
  // The panel itself cares about nothing else.
  let { snapshot }: { snapshot?: DehydratedSnapshot } = $props();

  let client = $state<Promise<JazzClient> | undefined>(undefined);
  const appId = env.PUBLIC_JAZZ_APP_ID!;
  const serverUrl = env.PUBLIC_JAZZ_SERVER_URL!;

  onMount(async () => {
    const secret = await BrowserAuthSecretStore.getOrCreateSecret({ appId });
    client = createJazzClient({ appId, serverUrl, secret });
  });
</script>

<JazzSvelteProvider {client} ssr={!!snapshot} {appId}>
  {#snippet children()}
    <TodoForm />
    <TodoList {snapshot} />
  {/snippet}
  {#snippet fallback()}
    <p class="mt-4 text-sm text-foreground/30 italic">Connecting…</p>
  {/snippet}
</JazzSvelteProvider>
