// examples/chat-react/src/components/chat/ChatReactions.tsx
import type { CoFeedEntry, ID } from "jazz-tools";
import { Suspense } from "react";
import clsx from "clsx";
import { useSuspenseCoState } from "jazz-tools/react";
import {
  HoverCard,
  HoverCardContent,
  HoverCardTrigger,
} from "@/components/ui/hover-card";
import { type ChatAccount, ChatAccountWithProfile, Message } from "@/schema";

interface ReactingUserProps {
  userId: ID<typeof ChatAccount>;
  currentUserId?: ID<typeof ChatAccount>;
}

const ReactingUser = ({ userId, currentUserId }: ReactingUserProps) => {
  const user = useSuspenseCoState(ChatAccountWithProfile, userId);

  return (
    <div>
      <span className={user.$jazz.id === currentUserId ? "font-semibold" : ""}>
        {user.$jazz.id === currentUserId
          ? "You"
          : user.profile?.name || "Anonymous"}
      </span>
    </div>
  );
};

interface ReactorsListProps {
  instances: { by?: { $jazz: { id: ID<typeof ChatAccount> } } | null }[];
  currentUserId: ID<typeof ChatAccount> | undefined;
}

const ReactorsList = ({ instances, currentUserId }: ReactorsListProps) => {
  return (
    <div className="flex flex-col gap-1">
      {instances?.map((r) => {
        if (!r.by) return null;
        return (
          <ReactingUser
            key={r.by.$jazz.id}
            userId={r.by.$jazz.id}
            currentUserId={currentUserId}
          />
        );
      })}
    </div>
  );
};

interface ReactionPillProps {
  emoji: string;
  count: number;
  iReacted: boolean;
  onToggle: () => void;
  children: React.ReactNode;
}

const ReactionPill = ({
  emoji,
  count,
  iReacted,
  onToggle,
  children,
}: ReactionPillProps) => {
  return (
    <HoverCard openDelay={200} closeDelay={100}>
      <HoverCardTrigger asChild>
        <button
          type="button"
          onPointerDown={(e) => e.stopPropagation()}
          onClick={(e) => {
            e.stopPropagation();
            onToggle();
          }}
          className={clsx(
            "text-xs px-1.5 py-0.5 rounded-full border shadow-sm transition-colors text-nowrap",
            iReacted
              ? "bg-primary text-primary-foreground border-primary-foreground"
              : "bg-background hover:bg-muted",
          )}
        >
          {emoji}
          {count > 1 && <span className="ml-1 opacity-75"> {count}</span>}
        </button>
      </HoverCardTrigger>

      <HoverCardContent
        side="top"
        className="w-fit min-w-25 p-2 text-xs"
        // Prevent clicking the card from triggering the message bubble dropdown
        onPointerDown={(e) => e.stopPropagation()}
      >
        <Suspense fallback={<div>Loading...</div>}>{children}</Suspense>
      </HoverCardContent>
    </HoverCard>
  );
};

interface MessageReactionsProps {
  messageId: ID<typeof Message>;
  currentUserId: ID<typeof ChatAccount> | undefined;
  isMe: boolean;
}

export const MessageReactions = ({
  messageId,
  currentUserId,
  isMe,
}: MessageReactionsProps) => {
  const message = useSuspenseCoState(Message, messageId, {
    resolve: {
      reactions: true,
    },
  });

  const reactions = Object.values(message.reactions.perAccount).reduce<
    Record<string, CoFeedEntry<string>[]>
  >((acc, item) => {
    const key = item.value;
    if (!acc[key]) acc[key] = [];
    acc[key].push(item);
    return acc;
  }, {});

  const myReaction = message.reactions.byMe?.value;

  const handleToggle = (emoji: string) => {
    const newValue = myReaction === emoji ? "" : emoji;
    message.reactions.$jazz.push(newValue);
  };

  const reactionEntries = Object.entries(reactions)
    .filter(([value, count]) => value && count && count.length > 0)
    .sort();

  if (reactionEntries.length === 0) return null;

  return (
    <div
      className={clsx(
        "absolute bottom-0 transform translate-y-[90%] flex gap-1 z-10 w-fit",
        isMe ? "right-0" : "left-0",
      )}
    >
      {reactionEntries.map(([emoji, instances]) => {
        if (!instances) return null;

        const count = instances.length;
        const iReacted = instances.some(
          (r) => r.by?.$jazz.id === currentUserId,
        );

        return (
          <ReactionPill
            key={emoji}
            emoji={emoji}
            count={count}
            iReacted={iReacted}
            onToggle={() => handleToggle(emoji)}
          >
            <ReactorsList instances={instances} currentUserId={currentUserId} />
          </ReactionPill>
        );
      })}
    </div>
  );
};

// examples/chat-svelte/src/components/chat/ChatReactions.svelte
<script lang="ts">
  import type { CoFeed, CoFeedEntry, ID } from 'jazz-tools';
  import { cn } from '@/lib/utils';
  import type { ChatAccount } from '@/lib/schema';

  interface Props {
    currentUserId: ID<typeof ChatAccount> | undefined;
    isMe: boolean;
    reactions: CoFeed<string>;
    onToggle: (emoji: string) => void;
  }

  let { currentUserId, isMe, reactions, onToggle }: Props = $props();

  const reactionEntries = $derived.by(() => {
    const perAccount = reactions.perAccount ?? {};
    const acc: Record<string, CoFeedEntry<string>[]> = {};
    for (const item of Object.values(perAccount)) {
      const key = item.value;
      if (!acc[key]) acc[key] = [];
      acc[key].push(item);
    }
    return Object.entries(acc)
      .filter(([, list]) => list && list.length > 0)
      .sort(([a], [b]) => a.localeCompare(b));
  });
</script>

{#if reactionEntries.length > 0}
  <div
    class={cn(
      'absolute bottom-0 z-10 flex w-fit translate-y-[90%] gap-1',
      isMe ? 'right-0' : 'left-0'
    )}
  >
    {#each reactionEntries as [emoji, instances]}
      {@const count = instances.length ?? 0}
      {@const iReacted = instances.some((r) => r.by?.$jazz.id === currentUserId) ?? false}
      <button
        type="button"
        class={cn(
          'text-nowrap rounded-full border px-1.5 py-0.5 text-xs shadow-sm transition-colors',
          iReacted
            ? 'border-primary-foreground bg-primary text-primary-foreground'
            : 'bg-background hover:bg-muted'
        )}
        onclick={(e) => {
          e.stopPropagation();
          onToggle(emoji);
        }}
        onpointerdown={(e) => e.stopPropagation()}
      >
        {emoji}
        {#if count > 1}
          <span class="ml-1 opacity-75">{count}</span>
        {/if}
      </button>
    {/each}
  </div>
{/if}
