// examples/chat-reatom-react/src/components/chat/ChatFile.tsx
import { reatomComponent } from "@reatom/react";
import { wrap } from "@reatom/core";
import { DownloadIcon } from "lucide-react";
import { Button } from "@/components/ui/button";
import { jazz } from "@/jazz";
import { downloadBlob, formatBytes } from "@/lib/utils";
import { app, type Attachment } from "../../../schema.js";

interface ChatFileProps {
  attachment: Attachment;
}

export const ChatFile = reatomComponent(({ attachment }: ChatFileProps) => {
  const { db } = jazz();
  const fileReadOptions = db.getConfig().serverUrl ? { tier: "edge" as const } : undefined;

  const handleDownload = async () => {
    const blob = await wrap(db.loadFileAsBlob(app, attachment.fileId, fileReadOptions));
    downloadBlob(blob, attachment.name);
  };

  return (
    <div className="rounded-xl my-2 flex flex-col">
      <span className="mb-2 wrap-anywhere">{attachment.name}</span>
      <Button
        variant="secondary"
        onClick={async (event) => {
          event.stopPropagation();
          await handleDownload();
        }}
        onPointerDown={(event) => {
          event.stopPropagation();
        }}
      >
        <DownloadIcon />
        Download{" "}
        {attachment.size > 0 && <span className="text-sm">({formatBytes(attachment.size)})</span>}
      </Button>
    </div>
  );
}, "ChatFile");

// examples/chat-svelte/src/components/chat/ChatFile.svelte
<script lang="ts">
  import type { ID } from 'jazz-tools';
  import { co } from 'jazz-tools';
  import { CoState } from 'jazz-tools/svelte';
  import { Download } from 'lucide-svelte';
  import { Button } from '@/components/ui/button';
  import { downloadBlob, formatBytes } from '@/lib/utils';
  import { toast } from 'svelte-sonner';

  interface Props {
    fileId: ID<typeof co.fileStream>;
  }

  let { fileId }: Props = $props();

  const fileStreamSchema = co.fileStream();
  const fileState = new CoState(fileStreamSchema, () => fileId);
  const file = $derived(fileState.current);

  const fileName = $derived(file.$isLoaded ? file.getMetadata()?.fileName : '');
  const fileSize = $derived(file.$isLoaded ? file.getMetadata()?.totalSizeBytes : 0);

  async function handleDownload() {
    if (!file.$isLoaded) return;
    const blob = file.toBlob();
    if (!blob) {
      toast.error('File was corrupted');
      return;
    }
    downloadBlob(blob, fileName || 'download');
  }
</script>

{#if file.$isLoaded}
  <div class="my-2 flex flex-col rounded-xl">
    <span class="mb-2 break-words">{fileName}</span>
    <Button variant="secondary" onclick={handleDownload}>
      <Download class="size-4" />
      Download
      {#if fileSize}
        <span class="text-sm">({formatBytes(fileSize)})</span>
      {/if}
    </Button>
  </div>
{:else}
  <div class="text-muted-foreground text-sm">{file.$jazz.loadingState ?? 'Loading'}...</div>
{/if}
