// examples/chat-reatom-react/src/components/chat/ChatMetadata.tsx
interface ChatMetadataProps {
  date: Date;
  senderName?: string;
}

export const ChatMetadata = ({ date, senderName }: ChatMetadataProps) => {
  const dateToString = date.toLocaleTimeString();
  return (
    <div className="text-xs gap-1 flex mb-1 text-muted-foreground">
      {senderName && <span>{senderName}</span>}
      <span>&bull;</span>
      <span>{dateToString}</span>
    </div>
  );
};

// examples/chat-svelte/src/components/chat/ChatMetadata.svelte
<script lang="ts">
  import { CoState } from 'jazz-tools/svelte';
  import { ChatAccountWithProfile } from '@/lib/schema';

  interface Props {
    date: number;
    sender?: string;
  }

  let { date, sender }: Props = $props();

  const senderState = $derived(new CoState(ChatAccountWithProfile, sender));
  const senderAccount = $derived(senderState.current);

  const dateStr = $derived(new Date(date).toLocaleTimeString());
</script>

<div class="text-muted-foreground mb-1 flex gap-1 text-xs">
  {#if senderAccount.$isLoaded}
    <span>{senderAccount.profile.name}</span>
  {/if}
  <span>&bull;</span>
  <span>{dateStr}</span>
</div>
