// examples/chat-react/src/components/chat/ChatMetadata.tsx
import { useCoState } from "jazz-tools/react";
import { ChatAccountWithProfile } from "@/schema";

interface ChatMetadataProps {
  date: number;
  sender?: string;
}

export const ChatMetadata = ({ date, sender }: ChatMetadataProps) => {
  const dateToString = new Date(date).toLocaleTimeString();
  const senderAccount = useCoState(ChatAccountWithProfile, sender);
  return (
    <div className="text-xs gap-1 flex mb-1 text-muted-foreground">
      {senderAccount.$isLoaded && <span>{senderAccount.profile.name}</span>}
      <span>&bull;</span>
      <span>{dateToString}</span>
    </div>
  );
};

// examples/chat-svelte/src/components/chat/ChatMetadata.svelte
<script lang="ts">
  import { CoState } from 'jazz-tools/svelte';
  import { ChatAccountWithProfile } from '@/lib/schema';

  interface Props {
    date: number;
    sender?: string;
  }

  let { date, sender }: Props = $props();

  const senderState = $derived(new CoState(ChatAccountWithProfile, sender));
  const senderAccount = $derived(senderState.current);

  const dateStr = $derived(new Date(date).toLocaleTimeString());
</script>

<div class="text-muted-foreground mb-1 flex gap-1 text-xs">
  {#if senderAccount.$isLoaded}
    <span>{senderAccount.profile.name}</span>
  {/if}
  <span>&bull;</span>
  <span>{dateStr}</span>
</div>
