// examples/chat-react/src/components/chat/ChatReactionPicker.tsx
import { useState } from "react";
import { SmilePlus } from "lucide-react";
import { useDb, useSession } from "jazz-tools/react";
import { Button } from "@/components/ui/button";
import {
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuSub,
  DropdownMenuSubContent,
  DropdownMenuSubTrigger,
} from "@/components/ui/dropdown-menu";
import { Input } from "@/components/ui/input";
import { app } from "../../../schema/app.js";

interface ReactionPickerProps {
  onPick: (emoji: string) => void;
  messageId: string;
}

export const ReactionPicker = ({ onPick, messageId }: ReactionPickerProps) => {
  const [customEmoji, setCustomEmoji] = useState("🍉");
  const db = useDb();
  const session = useSession();
  const presets = ["❤️", "👍", "🔥", "😂", "😮", "😢"];
  const emojiRegex =
    /^(\p{Extended_Pictographic}|\p{Emoji_Component}|\p{Emoji_Presentation}|\s)+$/u;

  const addReaction = (emoji: string) => {
    if (!session?.user_id) return;
    db.insert(app.reactions, {
      messageId,
      userId: session.user_id,
      emoji,
    });
    onPick(emoji);
  };

  return (
    <DropdownMenuSub>
      <DropdownMenuSubTrigger>
        <SmilePlus />
        React
      </DropdownMenuSubTrigger>

      <DropdownMenuSubContent className="w-36">
        <DropdownMenuLabel>Quick Reactions</DropdownMenuLabel>
        <div className="flex flex-wrap gap-2 p-2">
          {presets.map((emoji) => (
            <Button variant="outline" key={emoji} onClick={() => addReaction(emoji)}>
              {emoji}
            </Button>
          ))}
        </div>
        <DropdownMenuSeparator />
        <div className="p-2">
          <label className="text-xs text-muted-foreground mb-1 block" htmlFor="customEmoji">
            Custom
          </label>
          <div className="flex gap-2">
            <Input
              id="customEmoji"
              value={customEmoji}
              onChange={(e) => setCustomEmoji(e.target.value)}
              className="h-8"
              maxLength={2}
            />
            <Button
              size="sm"
              variant="outline"
              className="h-8 px-2"
              disabled={!customEmoji || !emojiRegex.test(customEmoji)}
              onClick={() => {
                addReaction(customEmoji);
                setCustomEmoji("");
              }}
            >
              Add
            </Button>
          </div>
        </div>
      </DropdownMenuSubContent>
    </DropdownMenuSub>
  );
};

// examples/chat-svelte/src/components/chat/ChatReactionPicker.svelte
<script lang="ts">
  import { SmilePlus } from 'lucide-svelte';
  import { Button } from '@/components/ui/button';
  import * as DropdownMenu from '@/components/ui/dropdown-menu';
  import { Input } from '@/components/ui/input';

  interface Props {
    onPick: (emoji: string) => void;
  }

  let { onPick }: Props = $props();

  let customEmoji = $state('🍉');
  const presets = ['❤️', '👍', '🔥', '😂', '😮', '😢'];

  // This regex is intended to allow users to only enter emojis
  const emojiRegex =
    /^(\p{Extended_Pictographic}|\p{Emoji_Component}|\p{Emoji_Presentation}|\s)+$/u;
</script>

<DropdownMenu.Sub>
  <DropdownMenu.SubTrigger>
    <SmilePlus class="size-4" />
    React
  </DropdownMenu.SubTrigger>
  <DropdownMenu.SubContent class="w-36">
    <DropdownMenu.Label>Quick Reactions</DropdownMenu.Label>
    <div class="flex flex-wrap gap-2 p-2">
      {#each presets as emoji}
        <Button variant="outline" onclick={() => onPick(emoji)}>
          {emoji}
        </Button>
      {/each}
    </div>
    <DropdownMenu.Separator />
    <div class="p-2">
      <label for="customEmoji" class="text-muted-foreground mb-1 block text-xs"> Custom </label>
      <div class="flex gap-2">
        <Input
          id="customEmoji"
          value={customEmoji}
          oninput={(e) => (customEmoji = e.currentTarget.value)}
          class="h-8"
          maxlength={2}
        />
        <Button
          size="sm"
          variant="outline"
          class="h-8 px-2"
          disabled={!customEmoji || !emojiRegex.test(customEmoji)}
          onclick={() => {
            onPick(customEmoji);
            customEmoji = '';
          }}
        >
          Add
        </Button>
      </div>
    </div>
  </DropdownMenu.SubContent>
</DropdownMenu.Sub>
