// packages/jazz-tools/src/react-core/use-all.ts
import * as React from "react";
import { type Usable, use } from "react";
import type { QueryBuilder } from "../runtime/db.js";
import { useJazzClient } from "./provider.js";

function useAllBase<T extends { id: string }>(
  query: QueryBuilder<T>,
  suspense: boolean,
): T[] | undefined {
  const { manager } = useJazzClient();

  const key = manager.makeQueryKey(query);
  const entry = manager.getCacheEntry<T>(key);
  const dispatch = React.useReducer((_, action) => action, entry.state)[1];

  React.useLayoutEffect(() => {
    const unsubscribe = entry.subscribe({
      onfulfilled: () => {
        dispatch(entry.state);
      },
      onDelta: () => {
        dispatch(entry.state);
      },
      onError: () => {
        dispatch(entry.state);
      },
    });

    return () => {
      unsubscribe();
    };
  }, [entry]);

  const state = entry.state;

  if (suspense) {
    if (state.status === "pending") {
      return use(state.promise as unknown as Usable<T[]>);
    }

    if (state.status === "rejected") {
      throw state.error;
    }
  }

  return state.status === "fulfilled" ? state.data : undefined;
}

export function useAll<T extends { id: string }>(query: QueryBuilder<T>): T[] | undefined {
  return useAllBase(query, false);
}

export function useAllSuspense<T extends { id: string }>(query: QueryBuilder<T>): T[] {
  return useAllBase(query, true) as T[];
}

// packages/jazz-tools/src/solid/use-all.ts
import { batch, createEffect, onCleanup, type Accessor } from "solid-js";
import { createStore, produce, reconcile } from "solid-js/store";
import { applyDelta } from "../reconcile-array.js";
import type { QueryBuilder, QueryOptions } from "../runtime/db.js";
import type { SubscriptionDelta } from "../runtime/subscription-manager.js";
import { useJazzClient } from "./provider.js";

export type UseAllResult<T extends { id: string }> = {
  data: T[] | undefined;
  loading: boolean;
  error: Error | null;
};

export function useAll<T extends { id: string }>(
  args: Accessor<{
    query: QueryBuilder<T> | undefined;
    options?: QueryOptions | undefined;
  }>,
): UseAllResult<T> {
  const client = useJazzClient();
  const [state, setState] = createStore<UseAllResult<T>>({
    data: undefined,
    loading: false,
    error: null,
  });

  createEffect(() => {
    const { query, options } = args();
    if (!query) {
      setState({
        data: undefined,
        loading: false,
        error: null,
      });
      return;
    }

    try {
      const key = client.manager.makeQueryKey(query, options);
      const entry = client.manager.getCacheEntry<T>(key);

      setState({
        data: entry.state.data,
        loading: entry.state.status === "pending",
        error: entry.state.error ? normalizeError(entry.state.error) : null,
      });

      const unsubscribe = entry.subscribe({
        onError: (error: unknown) =>
          setState({
            data: undefined,
            loading: false,
            error: normalizeError(error),
          }),
        onfulfilled: (nextData) =>
          setState({
            data: nextData,
            loading: false,
            error: null,
          }),
        onDelta: (delta: SubscriptionDelta<T>) =>
          batch(() => {
            if (state.data) {
              setState(
                "data",
                produce((current) => {
                  if (!current) return;
                  applyDelta(current, delta);
                }),
              );
            } else {
              setState("data", reconcile(delta.all));
            }
            setState("loading", false);
            setState("error", null);
          }),
      });

      onCleanup(unsubscribe);
    } catch (error) {
      setState({
        data: undefined,
        loading: false,
        error: normalizeError(error),
      });
    }
  });

  return state;
}

function normalizeError(error: unknown): Error {
  return error instanceof Error ? error : new Error(String(error));
}
