// packages/jazz-tools/src/solid/context/Provider.tsx
/**
 * @jsxImportSource solid-js
 */
import type { InstanceOfSchema } from "jazz-tools";
import {
  Account,
  type AccountClass,
  type AnyAccountSchema,
  type CoValueFromRaw,
} from "jazz-tools";
import {
  JazzBrowserContextManager,
  type JazzContextManagerProps,
} from "jazz-tools/browser";
import {
  type ParentProps,
  Show,
  createEffect,
  createMemo,
  createSignal,
  onCleanup,
} from "solid-js";
import {
  JazzContext,
  type JazzContextValue,
  JazzManagerContext,
} from "./jazz.js";

type JazzAccount = AccountClass<Account> & CoValueFromRaw<Account>;

export type JazzProviderProps<S extends JazzAccount | AnyAccountSchema> = {
  readonly enableSSR?: boolean;
} & JazzContextManagerProps<S>;

export const JazzProvider = <S extends JazzAccount | AnyAccountSchema>(
  props: ParentProps<JazzProviderProps<S>>,
) => {
  const jazzManager = createMemo(
    () =>
      new JazzBrowserContextManager<S>({
        useAnonymousFallback: props.enableSSR,
      }),
  );

  const [ctx, setCtx] = createSignal<JazzContextValue<InstanceOfSchema<S>>>();

  createEffect(() => {
    jazzManager()
      .createContext({
        sync: props.sync,
        storage: props.storage,
        guestMode: props.guestMode,
        AccountSchema: props.AccountSchema,
        defaultProfileName: props.defaultProfileName,
        onAnonymousAccountDiscarded: props.onAnonymousAccountDiscarded,
        onLogOut: props.onLogOut,
        logOutReplacement: props.logOutReplacement,
      })
      .catch((error) => {
        console.error("Error creating Jazz browser context:", error);
      });
  });

  const authStorage = () => jazzManager().getAuthSecretStorage();

  createEffect(() => {
    const unsubscribe = jazzManager().subscribe(() => {
      setCtx(jazzManager().getCurrentValue());
    });

    onCleanup(() => {
      unsubscribe();
    });
  });

  onCleanup(() => {
    jazzManager().done();
  });

  return (
    <Show when={ctx()}>
      {(ctxValue) => {
        return (
          <JazzContext.Provider value={ctxValue}>
            <JazzManagerContext.Provider value={jazzManager}>
              {props.children}
            </JazzManagerContext.Provider>
          </JazzContext.Provider>
        );
      }}
    </Show>
  );
};

// packages/jazz-react/src/provider.tsx
'use client'

import {
  JazzBrowserContextManager,
  JazzContextManagerProps,
} from "jazz-browser";
import { JazzContext, JazzContextManagerContext } from "jazz-react-core";
import {
  Account,
  AccountClass,
  AnyAccountSchema,
  CoValueFromRaw,
  InstanceOfSchema,
  JazzContextType,
} from "jazz-tools";
import React, { useEffect, useRef } from "react";

export type JazzProviderProps<
  S extends
    | (AccountClass<Account> & CoValueFromRaw<Account>)
    | AnyAccountSchema,
> = {
  children: React.ReactNode;
  /**
   * Renders children even before the account is loaded.
   *
   * For this reason useAccount may return null on the first render even when the
   * resolve option is not passed
   */
  experimental_enableSSR?: boolean;
} & JazzContextManagerProps<S>;

/** @category Context & Hooks */
export function JazzProvider<
  S extends
    | (AccountClass<Account> & CoValueFromRaw<Account>)
    | AnyAccountSchema,
>({
  children,
  guestMode,
  sync,
  storage,
  AccountSchema,
  defaultProfileName,
  onLogOut,
  logOutReplacement,
  onAnonymousAccountDiscarded,
  experimental_enableSSR,
}: JazzProviderProps<S>) {
  const [contextManager] = React.useState(
    () =>
      new JazzBrowserContextManager<S>({
        useAnonymousFallback: experimental_enableSSR,
      }),
  );

  const onLogOutRefCallback = useRefCallback(onLogOut);
  const logOutReplacementRefCallback = useRefCallback(logOutReplacement);
  const onAnonymousAccountDiscardedRefCallback = useRefCallback(
    onAnonymousAccountDiscarded,
  );
  const logoutReplacementActiveRef = useRef(false);
  logoutReplacementActiveRef.current = Boolean(logOutReplacement);

  const value = React.useSyncExternalStore<
    JazzContextType<InstanceOfSchema<S>> | undefined
  >(
    React.useCallback(
      (callback) => {
        const props = {
          AccountSchema,
          guestMode,
          sync,
          storage,
          defaultProfileName,
          onLogOut: onLogOutRefCallback,
          logOutReplacement: logoutReplacementActiveRef.current
            ? logOutReplacementRefCallback
            : undefined,
          onAnonymousAccountDiscarded: onAnonymousAccountDiscardedRefCallback,
        } satisfies JazzContextManagerProps<S>;

        if (contextManager.propsChanged(props)) {
          contextManager.createContext(props).catch((error) => {
            console.error("Error creating Jazz browser context:", error);
          });
        }

        return contextManager.subscribe(callback);
      },
      [sync, guestMode].concat(storage as any),
    ),
    () => contextManager.getCurrentValue(),
    () => contextManager.getCurrentValue(),
  );

  useEffect(() => {
    // In development mode we don't return a cleanup function because otherwise
    // the double effect execution would mark the context as done immediately.
    if (process.env.NODE_ENV === "development") return;

    return () => {
      contextManager.done();
    };
  }, []);

  return (
    <JazzContext.Provider value={value}>
      <JazzContextManagerContext.Provider value={contextManager}>
        {value && children}
      </JazzContextManagerContext.Provider>
    </JazzContext.Provider>
  );
}

function useRefCallback<T extends (...args: any[]) => any>(callback?: T) {
  const callbackRef = React.useRef(callback);
  callbackRef.current = callback;
  return useRef(
    (...args: Parameters<T>): ReturnType<T> => callbackRef.current?.(...args),
  ).current;
}
