// examples/docs/todo-client-localfirst-vue/src/TodoItem.vue
<script setup lang="ts">
import { computed } from "vue";
import { useDb, useAll } from "jazz-tools/vue";
import { app } from "../schema.js";

const props = defineProps<{ id: string }>();

const db = useDb();
const { data: todos } = useAll(() => app.todos.where({ id: props.id }).limit(1));
const todo = computed(() => todos.value?.[0]);
</script>

<template>
  <li v-if="todo" :class="{ done: todo.done }">
    <input
      type="checkbox"
      :checked="todo.done"
      @change="db.update(app.todos, props.id, { done: !todo.done })"
    />
    <span>{{ todo.title }}</span>
    <button @click="db.delete(app.todos, props.id)">&times;</button>
  </li>
</template>

// examples/docs/todo-client-localfirst-expo/src/TodoItem.tsx
import { Pressable, Text, View } from "react-native";
import { useDb, useAll } from "jazz-tools/react-native";
import { app } from "../schema";

export function TodoItem({ id }: { id: string }) {
  const db = useDb();
  const { data: todos = [] } = useAll(app.todos.where({ id }).limit(1));
  const [todo] = todos;

  if (!todo) return null;

  return (
    <View style={{ flexDirection: "row", alignItems: "center", gap: 8, paddingVertical: 4 }}>
      <Pressable onPress={() => db.update(app.todos, id, { done: !todo.done })}>
        <Text>{todo.done ? "☑" : "☐"}</Text>
      </Pressable>
      <Text style={{ flex: 1, textDecorationLine: todo.done ? "line-through" : "none" }}>
        {todo.title}
      </Text>
      <Pressable onPress={() => db.delete(app.todos, id)}>
        <Text>✕</Text>
      </Pressable>
    </View>
  );
}
