// examples/form-svelte/src/lib/components/OrderThumbnail.svelte
<script lang="ts">
  import { type Loaded } from 'jazz-tools';
  import { type BubbleTeaOrder } from '$lib/schema';

  type Props = {
    order: Loaded<typeof BubbleTeaOrder> | {
      baseTea: string;
      addOns: string[];
      deliveryDate: Date;
      withMilk: boolean;
      instructions?: string;
    };
  };

  let { order }: Props = $props();
</script>

<div class="border p-3 bg-gray-50 dark:bg-gray-800 rounded">
  <strong>
    {order.baseTea || "(No tea selected)"}
    {order.withMilk ? " milk " : " "}
    tea
  </strong>
  {#if order.addOns && order.addOns.length > 0}
    <p class="text-sm text-stone-600">
      with {order.addOns.join(", ").toLowerCase()}
    </p>
  {/if}
  {#if order.instructions}
    <p class="text-sm text-stone-600 italic">
      {order.instructions}
    </p>
  {/if}
  {#if order.deliveryDate}
    <p class="text-sm text-stone-600">
      Delivery: {order.deliveryDate.toLocaleDateString()}
    </p>
  {/if}
</div>

// examples/form/src/OrderThumbnail.tsx
import { Loaded } from "jazz-tools";
import { BubbleTeaOrder } from "./schema.ts";
import { OrderFormData } from "./OrderFormWithSaveButton.tsx";

export function OrderThumbnail({
  order,
}: {
  order: Loaded<typeof BubbleTeaOrder> | OrderFormData;
}) {
  const { baseTea, addOns, instructions, deliveryDate, withMilk } = order;
  const date = deliveryDate.toLocaleDateString();

  return (
    <a
      href={"id" in order ? `/#/order/${order.id}` : undefined}
      className="border p-3 flex justify-between items-start gap-3"
    >
      <div>
        <strong>
          {baseTea} {withMilk ? "milk " : ""} tea
        </strong>
        {addOns && addOns?.length > 0 && (
          <p className="text-sm text-stone-600">
            with {addOns?.join(", ").toLowerCase()}
          </p>
        )}
        {instructions && (
          <p className="text-sm text-stone-600 italic">{instructions}</p>
        )}
      </div>
      <div className="text-sm text-stone-600">{date}</div>
    </a>
  );
}
