// examples/docs/todo-client-localfirst-svelte/src/quickstart-add.svelte
<script lang="ts">
  import { getDb } from 'jazz-tools/svelte';
  import { app } from '../schema/app.js';

  const db = getDb();
  let title = $state('');
</script>

<form onsubmit={(e) => {
  e.preventDefault();
  db.insert(app.todos, { title, done: false });
  title = '';
}}>
  <input type="text" bind:value={title} placeholder="What needs to be done?" />
  <button type="submit">Add</button>
</form>

// examples/docs/todo-client-localfirst-react/src/quickstart-add.tsx
import { useState } from "react";
import { useDb } from "jazz-tools/react";
import { app } from "../schema/app.js";

export function AddTodo() {
  const db = useDb();
  const [title, setTitle] = useState("");

  return (
    <form
      onSubmit={(e) => {
        e.preventDefault();
        db.insert(app.todos, { title, done: false });
        setTitle("");
      }}
    >
      <input
        type="text"
        value={title}
        onChange={(e) => setTitle(e.target.value)}
        placeholder="What needs to be done?"
      />
      <button type="submit">Add</button>
    </form>
  );
}
