// examples/tanstack-form/src/CreateOrder.tsx
import { useIframeHashRouter } from "hash-slash";
import { CoPlainText } from "jazz-tools";
import { useAccount } from "jazz-tools/react";
import { LinkToHome } from "./LinkToHome.tsx";
import {
  BubbleTeaOrder,
  JazzAccount,
  ListOfBubbleTeaAddOns,
} from "./schema.ts";
import { OrderForm, OrderFormData } from "./OrderForm.tsx";

export function CreateOrder() {
  const { me } = useAccount(JazzAccount, {
    resolve: { root: { orders: true } },
  });
  const router = useIframeHashRouter();

  if (!me?.root) return;

  const addOrder = (draft: OrderFormData) => {
    const newOrder = BubbleTeaOrder.create({
      baseTea: draft.baseTea,
      deliveryDate: draft.deliveryDate,
      withMilk: draft.withMilk,
      addOns: ListOfBubbleTeaAddOns.create(draft.addOns),
      instructions: draft.instructions
        ? CoPlainText.create(draft.instructions)
        : undefined,
    });

    me.root.orders.push(newOrder);

    router.navigate("/");
  };

  const draftOrder: Partial<OrderFormData> = {
    baseTea: "Black",
    addOns: [],
    withMilk: false,
  };

  return (
    <>
      <LinkToHome />

      <h1 className="text-lg">
        <strong>Make a new bubble tea order 🧋</strong>
      </h1>

      <OrderForm order={draftOrder} onSubmit={addOrder} validateOn="submit" />
    </>
  );
}

// examples/form-svelte/src/lib/components/CreateOrder.svelte
<script lang="ts">
  import { AccountCoState } from 'jazz-tools/svelte';
  import { JazzAccount, BubbleTeaOrder, BubbleTeaBaseTeaTypes, ListOfBubbleTeaAddOns } from '$lib/schema';
  import OrderFormWithSaveButton from './OrderFormWithSaveButton.svelte';
  import LinkToHome from './LinkToHome.svelte';
  import { CoPlainText } from 'jazz-tools';

  const me = new AccountCoState(JazzAccount, {
    resolve: {
      profile: true,
      root: {
        orders: true
      }
    }
  });

  const orders = $derived(me.current?.root.orders);

  // Create a new order when component loads
  let newOrder = $state<any>(null);

  $effect(() => {
    if (orders && !newOrder) {
      const order = BubbleTeaOrder.create({
        baseTea: BubbleTeaBaseTeaTypes[0],
        addOns: ListOfBubbleTeaAddOns.create([], orders._owner),
        deliveryDate: new Date(),
        withMilk: false,
        instructions: CoPlainText.create(''),
      }, orders._owner);

      orders.push(order);
      newOrder = order;
    }
  });
</script>

<div>
  <LinkToHome />

  <h1 class="text-lg mb-4">
    <strong>Create your bubble tea order 🧋</strong>
  </h1>

  {#if newOrder}
    <OrderFormWithSaveButton order={newOrder} />
  {:else}
    <p>Creating order...</p>
  {/if}
</div>
