// examples/wequencer/apps/next-betterauth/app/dashboard/page.tsx
"use client";

import { authClient } from "@/lib/auth-client";
import { SessionBrowser } from "@/components/session-browser";

export default function DashboardPage() {
  const { data: session } = authClient.useSession();
  if (!session) return null;

  async function handleSignOut() {
    await authClient.signOut();
    window.location.assign("/");
  }

  return (
    <main className="dashboard">
      <header className="sequencer-header">
        <div>
          <p className="eyebrow">JAZZ EXAMPLE</p>
          <h1>Wequencer</h1>
        </div>
        <div className="auth-nav">
          <p>Hello, {session.user.name}</p>
          <button type="button" onClick={handleSignOut}>
            Sign out
          </button>
        </div>
      </header>
      <SessionBrowser userId={session.user.id} displayName={session.user.name} />
    </main>
  );
}

// starters/sveltekit-betterauth/src/routes/(authenticated)/dashboard/+page.svelte
<script lang="ts">
  import { goto } from "$app/navigation";
  import { authClient } from "$lib/auth-client";
  import TodoWidget from "$lib/TodoWidget.svelte";

  const session = authClient.useSession();

  async function handleSignOut() {
    await authClient.signOut();
    await goto("/");
  }
</script>

{#if $session.data}
  <main class="dashboard">
    <header>
      <img src="/jazz.svg" alt="Jazz" class="wordmark" />
      <div class="auth-nav">
        <p>Hello, {$session.data.user.name}</p>
        <button type="button" onclick={handleSignOut}>Sign out</button>
      </div>
    </header>
    <TodoWidget />
  </main>
{/if}
