// starters/next-betterauth/app/dashboard/page.tsx
"use client";

import Image from "next/image";
import { authClient } from "@/lib/auth-client";
import { TodoWidget } from "@/components/todo-widget";
import { useAuthActions } from "@/components/jazz-provider";

export default function DashboardPage() {
  const actions = useAuthActions();
  const { data: session } = authClient.useSession();
  if (!session) return null;

  async function handleSignOut() {
    try {
      await actions.signOut();
    } catch (cause) {
      actions.reportFailure(cause);
    }
  }

  return (
    <main className="dashboard">
      <header>
        <Image
          src="/jazz.svg"
          alt="Jazz"
          className="wordmark"
          width={80}
          height={24}
          style={{ width: "100%", height: "auto" }}
          loading="eager"
        />
        <div className="auth-nav">
          <p>Hello, {session.user.name}</p>
          <button type="button" onClick={handleSignOut}>
            Sign out
          </button>
        </div>
      </header>
      <TodoWidget />
    </main>
  );
}

// starters/sveltekit-betterauth/src/routes/(authenticated)/dashboard/+page.svelte
<script lang="ts">
  import { goto } from "$app/navigation";
  import { authClient } from "$lib/auth-client";
  import TodoWidget from "$lib/TodoWidget.svelte";
  import { getAuthActions } from "$lib/auth-actions";

  const session = authClient.useSession();
  const auth = getAuthActions();

  async function handleSignOut() {
    try {
      await auth.signOut();
      await goto("/");
    } catch (cause) {
      auth.reportFailure(cause);
    }
  }
</script>

{#if $session.data}
  <main class="dashboard">
    <header>
      <img src="/jazz.svg" alt="Jazz" class="wordmark" />
      <div class="auth-nav">
        <p>Hello, {$session.data.user.name}</p>
        <button type="button" onclick={handleSignOut}>Sign out</button>
      </div>
    </header>
    <TodoWidget />
  </main>
{/if}
