// starters/nuxt-betterauth/pages/dashboard/index.vue
<template>
  <main class="dashboard">
    <header>
      <img src="/jazz.svg" alt="Jazz" class="wordmark" />
      <div class="auth-nav">
        <p v-if="sessionStore.data">Hello, {{ sessionStore.data.user.name }}</p>
        <button type="button" @click="signOut">Sign out</button>
      </div>
    </header>
    <TodoWidget />
  </main>
</template>

<script setup lang="ts">
import { createAuthClient } from "better-auth/vue";
import TodoWidget from "~/components/TodoWidget.client.vue";

definePageMeta({ layout: "authenticated", middleware: ["auth"] });

const authClient = createAuthClient();
const sessionStore = authClient.useSession();

async function signOut() {
  await authClient.signOut();
  window.location.assign("/");
}
</script>

// starters/sveltekit-betterauth/src/routes/(authenticated)/dashboard/+page.svelte
<script lang="ts">
  import { goto } from "$app/navigation";
  import { authClient } from "$lib/auth-client";
  import TodoWidget from "$lib/TodoWidget.svelte";

  const session = authClient.useSession();

  async function handleSignOut() {
    await authClient.signOut();
    await goto("/");
  }
</script>

{#if $session.data}
  <main class="dashboard">
    <header>
      <img src="/jazz.svg" alt="Jazz" class="wordmark" />
      <div class="auth-nav">
        <p>Hello, {$session.data.user.name}</p>
        <button type="button" onclick={handleSignOut}>Sign out</button>
      </div>
    </header>
    <TodoWidget />
  </main>
{/if}
